import { test, expect } from './_coverage';
import postgres from 'postgres';
import { bootHarness, truncateDashboardState } from './_harness';

// Concurrent-operators acceptance per plan §"Test strategy >
// integration > concurrent-operators.spec.ts" + spec edge case
// "Concurrent operators" + FR-002f.
//
// Two distinct operator accounts logged in simultaneously must:
//   - both work without session collision
//   - see identical data
//   - have no per-operator-private surface (FR-002f: identical
//     privileges, no role hierarchy)

async function seedOperator(
  env: Awaited<ReturnType<typeof bootHarness>>,
  email: string,
  name: string,
) {
  await fetch(`${env.BETTER_AUTH_URL}/api/auth/sign-up/email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: env.BETTER_AUTH_URL },
    body: JSON.stringify({ email, password: 'integration-pw-1', name }),
  });
}

async function login(
  page: import('@playwright/test').Page,
  email: string,
) {
  await page.goto('/login');
  await page.locator('input[name=email]').fill(email);
  await page.locator('input[name=password]').fill('integration-pw-1');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL((url) => url.pathname === '/');
}

test.describe('concurrent operators', () => {
  test.beforeEach(async () => {
    const env = await bootHarness();
    await truncateDashboardState(env);
  });

  test('two distinct operator accounts can be logged in simultaneously without collision', async ({
    browser,
  }) => {
    const env = await bootHarness();
    await seedOperator(env, 'op-a@example.com', 'Op A');
    await seedOperator(env, 'op-b@example.com', 'Op B');

    const ctxA = await browser.newContext();
    const pageA = await ctxA.newPage();
    await login(pageA, 'op-a@example.com');

    const ctxB = await browser.newContext();
    const pageB = await ctxB.newPage();
    await login(pageB, 'op-b@example.com');

    // Both contexts navigate the same surface simultaneously.
    await Promise.all([pageA.goto('/admin/invites'), pageB.goto('/admin/invites')]);
    await expect(pageA.getByRole('heading')).toBeVisible();
    await expect(pageB.getByRole('heading')).toBeVisible();

    await ctxA.close();
    await ctxB.close();
  });

  test('an invite generated by operator A is visible to operator B (FR-002f: identical privileges)', async ({
    browser,
  }) => {
    const env = await bootHarness();
    await seedOperator(env, 'op-a@example.com', 'Op A');
    await seedOperator(env, 'op-b@example.com', 'Op B');

    const ctxA = await browser.newContext();
    const pageA = await ctxA.newPage();
    await login(pageA, 'op-a@example.com');
    await pageA.goto('/admin/invites');
    await pageA.getByTestId('generate-invite').click();
    await expect(pageA.getByTestId('invite-link').first()).toBeVisible({ timeout: 10_000 });

    // Operator B sees the same pending invite.
    const ctxB = await browser.newContext();
    const pageB = await ctxB.newPage();
    await login(pageB, 'op-b@example.com');
    await pageB.goto('/admin/invites');
    await expect(pageB.getByTestId('invite-link').first()).toBeVisible({ timeout: 10_000 });

    await ctxA.close();
    await ctxB.close();
  });
});
