import type { Config } from 'drizzle-kit';

// Drizzle config for the dashboard.
//
// `dashboard/drizzle/schema.ts` is partitioned into two sections:
//
//   1. Introspected supervisor-owned tables (tickets, ticket_transitions,
//      agents, agent_instances, event_outbox, agent_role_secrets,
//      vault_access_log, secret_metadata) — generated by `drizzle-kit pull`
//      via scripts/pull-supervisor-schema.ts. The dashboard MUST NOT
//      generate diff-migrations targeting these tables; goose owns them
//      (FR-020).
//
//   2. Dashboard-owned tables (better-auth core: users, sessions, accounts,
//      verifications + operator_invites + theme_preference column on
//      users) — hand-written below the introspected section. T004 lands
//      these alongside the first Drizzle-generated migration.
//
// `out` is the only directory drizzle-kit writes to during `generate`.
// `tablesFilter` constrains diff-generation to the dashboard-owned table
// names so the goose-managed tables are NEVER targeted by drizzle-kit
// migrations even if they end up in the schema file.
export default {
  schema: './drizzle/schema.ts',
  out: './drizzle/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DASHBOARD_APP_DSN ?? '',
  },
  // Allow-list: only dashboard-owned tables are eligible for diff-generation.
  // Supervisor-owned tables in schema.ts are introspected types only.
  tablesFilter: ['users', 'sessions', 'accounts', 'verifications', 'operator_invites'],
} satisfies Config;
