import type { Config } from 'drizzle-kit';

// Drizzle config for the dashboard.
//
// `dashboard/drizzle/schema.ts` is partitioned into two sections:
//
//   1. Introspected supervisor-owned tables (tickets, ticket_transitions,
//      agents, agent_instances, event_outbox, agent_role_secrets,
//      vault_access_log, secret_metadata) — generated by `drizzle-kit pull`
//      via scripts/pull-supervisor-schema.ts. The dashboard MUST NOT
//      generate diff-migrations targeting these tables; goose owns them
//      (FR-020).
//
//   2. Dashboard-owned tables (better-auth core: users, sessions, accounts,
//      verifications + operator_invites + theme_preference column on
//      users) — hand-written below the introspected section. T004 lands
//      these alongside the first Drizzle-generated migration.
//
// `out` is the only directory drizzle-kit writes to during `generate`.
// Points `schema` at schema.dashboard.ts (NOT the umbrella schema.ts
// that re-exports both supervisor and dashboard tables). drizzle-kit
// generate diffs the schema file's exports against the database;
// pointing it at the dashboard-only file makes the generated SQL
// cover only those five tables, regardless of whether the supervisor
// section is present in the introspected types.
//
// Runtime clients (lib/db/{appClient,vaultRoClient}.ts) still import
// from drizzle/schema.ts so query type-safety covers ALL tables;
// only drizzle-kit's tooling reads this narrower file.
export default {
  schema: './drizzle/schema.dashboard.ts',
  out: './drizzle/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DASHBOARD_APP_DSN ?? '',
  },
} satisfies Config;
