// drizzle/schema.ts is the single import surface for the Drizzle
// clients (lib/db/{appClient,vaultRoClient}.ts). It re-exports
// from two backing files that have very different lifecycles:
//
//   - schema.supervisor.ts is regenerated by `bun run drizzle:pull`
//     against the M2-arc migrations. Treat it as introspected
//     output; never hand-edit. Drizzle-kit generate is allow-listed
//     in drizzle.config.ts to skip these tables — goose owns them.
//
//   - schema.dashboard.ts is hand-written. Drizzle migrations target
//     these tables (better-auth core + operator_invites + the
//     theme_preference column on users). T004 lands the first
//     migration here; subsequent edits to the dashboard schema
//     happen in this file.
//
// Re-exports are wildcard so both files contribute their named
// exports to the canonical surface.

export * from './schema.supervisor';
export * from './schema.dashboard';
