// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_instances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningByDepartment = `-- name: CountRunningByDepartment :one
SELECT COUNT(*) FROM agent_instances
WHERE department_id = $1 AND status = 'running'
`

func (q *Queries) CountRunningByDepartment(ctx context.Context, departmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRunningInstance = `-- name: InsertRunningInstance :one
INSERT INTO agent_instances (department_id, ticket_id, pid, status)
VALUES ($1, $2, $3, 'running')
RETURNING id
`

type InsertRunningInstanceParams struct {
	DepartmentID pgtype.UUID
	TicketID     pgtype.UUID
	Pid          *int32
}

func (q *Queries) InsertRunningInstance(ctx context.Context, arg InsertRunningInstanceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRunningInstance, arg.DepartmentID, arg.TicketID, arg.Pid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const recoverStaleRunning = `-- name: RecoverStaleRunning :execrows
UPDATE agent_instances
SET status = 'failed',
    exit_reason = 'supervisor_restarted',
    finished_at = NOW()
WHERE status = 'running'
  AND started_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) RecoverStaleRunning(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleRunning)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstanceTerminal = `-- name: UpdateInstanceTerminal :exec
UPDATE agent_instances
SET status = $2,
    finished_at = NOW(),
    exit_reason = $3
WHERE id = $1
`

type UpdateInstanceTerminalParams struct {
	ID         pgtype.UUID
	Status     string
	ExitReason *string
}

func (q *Queries) UpdateInstanceTerminal(ctx context.Context, arg UpdateInstanceTerminalParams) error {
	_, err := q.db.Exec(ctx, updateInstanceTerminal, arg.ID, arg.Status, arg.ExitReason)
	return err
}

const updateInstanceTerminalWithCost = `-- name: UpdateInstanceTerminalWithCost :exec
UPDATE agent_instances
SET status = $2,
    finished_at = NOW(),
    exit_reason = $3,
    total_cost_usd = $4
WHERE id = $1
`

type UpdateInstanceTerminalWithCostParams struct {
	ID           pgtype.UUID
	Status       string
	ExitReason   *string
	TotalCostUsd pgtype.Numeric
}

func (q *Queries) UpdateInstanceTerminalWithCost(ctx context.Context, arg UpdateInstanceTerminalWithCostParams) error {
	_, err := q.db.Exec(ctx, updateInstanceTerminalWithCost,
		arg.ID,
		arg.Status,
		arg.ExitReason,
		arg.TotalCostUsd,
	)
	return err
}

const updatePID = `-- name: UpdatePID :exec
UPDATE agent_instances
SET pid = $2
WHERE id = $1
`

type UpdatePIDParams struct {
	ID  pgtype.UUID
	Pid *int32
}

func (q *Queries) UpdatePID(ctx context.Context, arg UpdatePIDParams) error {
	_, err := q.db.Exec(ctx, updatePID, arg.ID, arg.Pid)
	return err
}
