// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_role_secrets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO agent_role_secrets
    (role_slug, secret_path, env_var_name, customer_id, granted_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertGrantParams struct {
	RoleSlug   string
	SecretPath string
	EnvVarName string
	CustomerID pgtype.UUID
	GrantedBy  string
}

// Used only by migrations at M2.3; M4 will layer on top. The trigger on
// agent_role_secrets rebuilds secret_metadata.allowed_role_slugs automatically.
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.RoleSlug,
		arg.SecretPath,
		arg.EnvVarName,
		arg.CustomerID,
		arg.GrantedBy,
	)
	return err
}

const listGrantsForRole = `-- name: ListGrantsForRole :many
SELECT env_var_name, secret_path, customer_id
  FROM agent_role_secrets
 WHERE role_slug = $1 AND customer_id = $2
 ORDER BY env_var_name
`

type ListGrantsForRoleParams struct {
	RoleSlug   string
	CustomerID pgtype.UUID
}

type ListGrantsForRoleRow struct {
	EnvVarName string
	SecretPath string
	CustomerID pgtype.UUID
}

// Rule 2 per-role grant query (FR-409). Returns zero rows for a role with
// no grants; callers skip the Infisical fetch in that case.
func (q *Queries) ListGrantsForRole(ctx context.Context, arg ListGrantsForRoleParams) ([]ListGrantsForRoleRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForRole, arg.RoleSlug, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForRoleRow
	for rows.Next() {
		var i ListGrantsForRoleRow
		if err := rows.Scan(&i.EnvVarName, &i.SecretPath, &i.CustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
