// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentByDepartmentAndRole = `-- name: GetAgentByDepartmentAndRole :one
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at FROM agents
WHERE department_id = $1 AND role_slug = $2 AND status = 'active'
`

type GetAgentByDepartmentAndRoleParams struct {
	DepartmentID pgtype.UUID
	RoleSlug     string
}

func (q *Queries) GetAgentByDepartmentAndRole(ctx context.Context, arg GetAgentByDepartmentAndRoleParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByDepartmentAndRole, arg.DepartmentID, arg.RoleSlug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.AgentMd,
		&i.Model,
		&i.Skills,
		&i.McpTools,
		&i.ListensFor,
		&i.PalaceWing,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.AgentMd,
		&i.Model,
		&i.Skills,
		&i.McpTools,
		&i.ListensFor,
		&i.PalaceWing,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAgents = `-- name: ListActiveAgents :many
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at FROM agents
WHERE status = 'active'
ORDER BY department_id, role_slug
`

func (q *Queries) ListActiveAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listActiveAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.RoleSlug,
			&i.AgentMd,
			&i.Model,
			&i.Skills,
			&i.McpTools,
			&i.ListensFor,
			&i.PalaceWing,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentMD = `-- name: UpdateAgentMD :exec
UPDATE agents
SET agent_md = $2
WHERE id = $1
`

type UpdateAgentMDParams struct {
	ID      pgtype.UUID
	AgentMd string
}

func (q *Queries) UpdateAgentMD(ctx context.Context, arg UpdateAgentMDParams) error {
	_, err := q.db.Exec(ctx, updateAgentMD, arg.ID, arg.AgentMd)
	return err
}
