// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentsByRoleSlug = `-- name: CountAgentsByRoleSlug :one
SELECT count(*)::int8 AS count FROM agents WHERE role_slug = $1
`

// M5.3 ambiguity check: returns the number of agents matching the
// given role_slug. Verbs reject calls where count > 1 to force the
// operator to disambiguate.
func (q *Queries) CountAgentsByRoleSlug(ctx context.Context, roleSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentsByRoleSlug, roleSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAgentByRoleSlug = `-- name: FindAgentByRoleSlug :one
SELECT id, department_id, role_slug, status FROM agents
WHERE role_slug = $1
ORDER BY department_id
LIMIT 1
`

type FindAgentByRoleSlugRow struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	RoleSlug     string
	Status       string
}

// M5.3: chat verbs accept role_slug as a single string. The agents
// schema has UNIQUE (department_id, role_slug); within active rows,
// a slug may appear in multiple departments. Returns the single
// match deterministically ordered by department_id; verbs use
// CountAgentsByRoleSlug first to reject multi-department slugs as
// ambiguous.
func (q *Queries) FindAgentByRoleSlug(ctx context.Context, roleSlug string) (FindAgentByRoleSlugRow, error) {
	row := q.db.QueryRow(ctx, findAgentByRoleSlug, roleSlug)
	var i FindAgentByRoleSlugRow
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.Status,
	)
	return i, err
}

const getAgentByDepartmentAndRole = `-- name: GetAgentByDepartmentAndRole :one
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at, mcp_config, updated_at, image_digest, runtime_caps, egress_grant_jsonb, mcp_servers_jsonb, last_grandfathered_at, host_uid FROM agents
WHERE department_id = $1 AND role_slug = $2 AND status = 'active'
`

type GetAgentByDepartmentAndRoleParams struct {
	DepartmentID pgtype.UUID
	RoleSlug     string
}

func (q *Queries) GetAgentByDepartmentAndRole(ctx context.Context, arg GetAgentByDepartmentAndRoleParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByDepartmentAndRole, arg.DepartmentID, arg.RoleSlug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.AgentMd,
		&i.Model,
		&i.Skills,
		&i.McpTools,
		&i.ListensFor,
		&i.PalaceWing,
		&i.Status,
		&i.CreatedAt,
		&i.McpConfig,
		&i.UpdatedAt,
		&i.ImageDigest,
		&i.RuntimeCaps,
		&i.EgressGrantJsonb,
		&i.McpServersJsonb,
		&i.LastGrandfatheredAt,
		&i.HostUid,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at, mcp_config, updated_at, image_digest, runtime_caps, egress_grant_jsonb, mcp_servers_jsonb, last_grandfathered_at, host_uid FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.AgentMd,
		&i.Model,
		&i.Skills,
		&i.McpTools,
		&i.ListensFor,
		&i.PalaceWing,
		&i.Status,
		&i.CreatedAt,
		&i.McpConfig,
		&i.UpdatedAt,
		&i.ImageDigest,
		&i.RuntimeCaps,
		&i.EgressGrantJsonb,
		&i.McpServersJsonb,
		&i.LastGrandfatheredAt,
		&i.HostUid,
	)
	return i, err
}

const listActiveAgents = `-- name: ListActiveAgents :many
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at, mcp_config, updated_at, image_digest, runtime_caps, egress_grant_jsonb, mcp_servers_jsonb, last_grandfathered_at, host_uid FROM agents
WHERE status = 'active'
ORDER BY department_id, role_slug
`

func (q *Queries) ListActiveAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listActiveAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.RoleSlug,
			&i.AgentMd,
			&i.Model,
			&i.Skills,
			&i.McpTools,
			&i.ListensFor,
			&i.PalaceWing,
			&i.Status,
			&i.CreatedAt,
			&i.McpConfig,
			&i.UpdatedAt,
			&i.ImageDigest,
			&i.RuntimeCaps,
			&i.EgressGrantJsonb,
			&i.McpServersJsonb,
			&i.LastGrandfatheredAt,
			&i.HostUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfigFields = `-- name: UpdateAgentConfigFields :exec
UPDATE agents
   SET model = $1,
       agent_md = $2,
       palace_wing = $3
 WHERE id = $4
`

type UpdateAgentConfigFieldsParams struct {
	Model      string
	AgentMd    string
	PalaceWing *string
	ID         pgtype.UUID
}

// M5.3 garrison-mutate.edit_agent_config. Partial-update of operator-
// editable agent fields. Verb resolves COALESCE on the Go side after
// the leak-scan pass.
func (q *Queries) UpdateAgentConfigFields(ctx context.Context, arg UpdateAgentConfigFieldsParams) error {
	_, err := q.db.Exec(ctx, updateAgentConfigFields,
		arg.Model,
		arg.AgentMd,
		arg.PalaceWing,
		arg.ID,
	)
	return err
}

const updateAgentMD = `-- name: UpdateAgentMD :exec
UPDATE agents
SET agent_md = $2
WHERE id = $1
`

type UpdateAgentMDParams struct {
	ID      pgtype.UUID
	AgentMd string
}

func (q *Queries) UpdateAgentMD(ctx context.Context, arg UpdateAgentMDParams) error {
	_, err := q.db.Exec(ctx, updateAgentMD, arg.ID, arg.AgentMd)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = $1 WHERE id = $2
`

type UpdateAgentStatusParams struct {
	Status string
	ID     pgtype.UUID
}

// M5.3 garrison-mutate.pause_agent / resume_agent. Sets the agent's
// status; pause sets 'paused', resume sets 'active'. Existing M2.x
// spawn loop already filters on status='active', so paused agents
// naturally stop receiving new spawns.
func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.Status, arg.ID)
	return err
}
