// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_instances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningByDepartment = `-- name: CountRunningByDepartment :one
SELECT COUNT(*) FROM agent_instances
WHERE department_id = $1 AND status = 'running'
`

func (q *Queries) CountRunningByDepartment(ctx context.Context, departmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgentInstanceRunWindow = `-- name: GetAgentInstanceRunWindow :one
SELECT ai.id,
       ai.started_at,
       ai.finished_at,
       ai.department_id,
       ai.role_slug,
       a.palace_wing
FROM agent_instances ai
LEFT JOIN agents a
  ON a.department_id = ai.department_id AND a.role_slug = ai.role_slug
WHERE ai.id = $1
`

type GetAgentInstanceRunWindowRow struct {
	ID           pgtype.UUID
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	DepartmentID pgtype.UUID
	RoleSlug     string
	PalaceWing   *string
}

// Resolves agent_instance_id → (started_at, finished_at, palace_wing, role_slug)
// for the hygiene checker (FR-213). Palace wing comes from the agents table
// via the (department_id, role_slug) key.
func (q *Queries) GetAgentInstanceRunWindow(ctx context.Context, id pgtype.UUID) (GetAgentInstanceRunWindowRow, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceRunWindow, id)
	var i GetAgentInstanceRunWindowRow
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.PalaceWing,
	)
	return i, err
}

const insertRunningInstance = `-- name: InsertRunningInstance :one
INSERT INTO agent_instances (department_id, ticket_id, pid, status, role_slug)
VALUES ($1, $2, $3, 'running', $4)
RETURNING id
`

type InsertRunningInstanceParams struct {
	DepartmentID pgtype.UUID
	TicketID     pgtype.UUID
	Pid          *int32
	RoleSlug     string
}

func (q *Queries) InsertRunningInstance(ctx context.Context, arg InsertRunningInstanceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRunningInstance,
		arg.DepartmentID,
		arg.TicketID,
		arg.Pid,
		arg.RoleSlug,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const recoverStaleRunning = `-- name: RecoverStaleRunning :execrows
UPDATE agent_instances
SET status = 'failed',
    exit_reason = 'supervisor_restarted',
    finished_at = NOW()
WHERE status = 'running'
  AND started_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) RecoverStaleRunning(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleRunning)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectAgentInstanceFinalizedState = `-- name: SelectAgentInstanceFinalizedState :one
SELECT
    ai.status,
    ai.exit_reason,
    EXISTS(
        SELECT 1 FROM ticket_transitions tt
        WHERE tt.triggered_by_agent_instance_id = ai.id
    ) AS has_transition
FROM agent_instances ai
WHERE ai.id = $1
`

type SelectAgentInstanceFinalizedStateRow struct {
	Status        string
	ExitReason    *string
	HasTransition bool
}

// M2.2.1 FR-260 + T008: the finalize MCP server calls this on every
// tool call to detect the already-committed state (Clarification
// 2026-04-23 Q2). The hygiene listener/sweep also uses exit_reason to
// route between the finalize path (EvaluateFinalizeOutcome) and the
// legacy M2.2 palace-query path (Evaluate).
func (q *Queries) SelectAgentInstanceFinalizedState(ctx context.Context, id pgtype.UUID) (SelectAgentInstanceFinalizedStateRow, error) {
	row := q.db.QueryRow(ctx, selectAgentInstanceFinalizedState, id)
	var i SelectAgentInstanceFinalizedStateRow
	err := row.Scan(&i.Status, &i.ExitReason, &i.HasTransition)
	return i, err
}

const updateInstanceTerminal = `-- name: UpdateInstanceTerminal :exec
UPDATE agent_instances
SET status = $2,
    finished_at = NOW(),
    exit_reason = $3
WHERE id = $1
`

type UpdateInstanceTerminalParams struct {
	ID         pgtype.UUID
	Status     string
	ExitReason *string
}

func (q *Queries) UpdateInstanceTerminal(ctx context.Context, arg UpdateInstanceTerminalParams) error {
	_, err := q.db.Exec(ctx, updateInstanceTerminal, arg.ID, arg.Status, arg.ExitReason)
	return err
}

const updateInstanceTerminalWithCost = `-- name: UpdateInstanceTerminalWithCost :exec
UPDATE agent_instances
SET status = $2,
    finished_at = NOW(),
    exit_reason = $3,
    total_cost_usd = $4
WHERE id = $1
`

type UpdateInstanceTerminalWithCostParams struct {
	ID           pgtype.UUID
	Status       string
	ExitReason   *string
	TotalCostUsd pgtype.Numeric
}

func (q *Queries) UpdateInstanceTerminalWithCost(ctx context.Context, arg UpdateInstanceTerminalWithCostParams) error {
	_, err := q.db.Exec(ctx, updateInstanceTerminalWithCost,
		arg.ID,
		arg.Status,
		arg.ExitReason,
		arg.TotalCostUsd,
	)
	return err
}

const updateInstanceTerminalWithCostAndWakeup = `-- name: UpdateInstanceTerminalWithCostAndWakeup :exec
UPDATE agent_instances
SET status = $2,
    finished_at = NOW(),
    exit_reason = $3,
    total_cost_usd = $4,
    wake_up_status = $5
WHERE id = $1
`

type UpdateInstanceTerminalWithCostAndWakeupParams struct {
	ID           pgtype.UUID
	Status       string
	ExitReason   *string
	TotalCostUsd pgtype.Numeric
	WakeUpStatus *string
}

func (q *Queries) UpdateInstanceTerminalWithCostAndWakeup(ctx context.Context, arg UpdateInstanceTerminalWithCostAndWakeupParams) error {
	_, err := q.db.Exec(ctx, updateInstanceTerminalWithCostAndWakeup,
		arg.ID,
		arg.Status,
		arg.ExitReason,
		arg.TotalCostUsd,
		arg.WakeUpStatus,
	)
	return err
}

const updatePID = `-- name: UpdatePID :exec
UPDATE agent_instances
SET pid = $2
WHERE id = $1
`

type UpdatePIDParams struct {
	ID  pgtype.UUID
	Pid *int32
}

func (q *Queries) UpdatePID(ctx context.Context, arg UpdatePIDParams) error {
	_, err := q.db.Exec(ctx, updatePID, arg.ID, arg.Pid)
	return err
}
