// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortSessionsWithAbortedMessages = `-- name: AbortSessionsWithAbortedMessages :exec
UPDATE chat_sessions
   SET status = 'aborted', ended_at = NOW()
 WHERE status = 'active'
   AND id IN (
       SELECT DISTINCT session_id
         FROM chat_messages
        WHERE status = 'aborted' AND error_kind = $1
   )
`

// Companion to MarkPendingMessagesAborted: rolls the parent session to
// aborted state. Run in the same tx so the sweep is atomic.
func (q *Queries) AbortSessionsWithAbortedMessages(ctx context.Context, errorKind *string) error {
	_, err := q.db.Exec(ctx, abortSessionsWithAbortedMessages, errorKind)
	return err
}

const commitAssistantTerminal = `-- name: CommitAssistantTerminal :exec
UPDATE chat_messages
   SET status              = $1,
       content             = $2,
       tokens_input        = $3,
       tokens_output       = $4,
       cost_usd            = $5,
       error_kind          = $6,
       raw_event_envelope  = $7,
       terminated_at       = NOW()
 WHERE id = $8
`

type CommitAssistantTerminalParams struct {
	Status           string
	Content          *string
	TokensInput      *int32
	TokensOutput     *int32
	CostUsd          pgtype.Numeric
	ErrorKind        *string
	RawEventEnvelope []byte
	ID               pgtype.UUID
}

// Single UPDATE that commits the assistant turn at terminal time:
// content + cost + tokens + raw_event_envelope + status + terminated_at.
// Called inside the same tx as RollUpSessionCost + the audit pg_notify.
func (q *Queries) CommitAssistantTerminal(ctx context.Context, arg CommitAssistantTerminalParams) error {
	_, err := q.db.Exec(ctx, commitAssistantTerminal,
		arg.Status,
		arg.Content,
		arg.TokensInput,
		arg.TokensOutput,
		arg.CostUsd,
		arg.ErrorKind,
		arg.RawEventEnvelope,
		arg.ID,
	)
	return err
}

const countInflightMessages = `-- name: CountInflightMessages :one
SELECT COUNT(*)::INTEGER AS count
  FROM chat_messages
 WHERE session_id = $1
   AND status IN ('pending', 'streaming')
`

func (q *Queries) CountInflightMessages(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInflightMessages, sessionID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createChatSession = `-- name: CreateChatSession :one

INSERT INTO chat_sessions (id, started_by_user_id, status, total_cost_usd, started_at)
VALUES (gen_random_uuid(), $1, 'active', 0, NOW())
RETURNING id, started_by_user_id, started_at, ended_at, status, total_cost_usd, claude_session_label, is_archived
`

// M5.1 chat backend queries.
// Read/write patterns for chat_sessions + chat_messages used by the
// supervisor's internal/chat/ package.
// Operator-initiated session creation. The dashboard server action
// INSERTs alongside the first chat_messages row in one tx; supervisor
// never lazy-creates sessions per FR-080.
func (q *Queries) CreateChatSession(ctx context.Context, startedByUserID pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession, startedByUserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.StartedByUserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TotalCostUsd,
		&i.ClaudeSessionLabel,
		&i.IsArchived,
	)
	return i, err
}

const findOrphanedOperatorSessions = `-- name: FindOrphanedOperatorSessions :many
SELECT cm.session_id AS session_id,
       cm.id AS operator_message_id,
       cm.turn_index AS orphan_turn_index
  FROM chat_messages cm
  JOIN chat_sessions cs ON cs.id = cm.session_id
 WHERE cs.status = 'active'
   AND cm.role = 'operator'
   AND cm.created_at < $1
   AND cm.turn_index = (
       SELECT MAX(turn_index)
         FROM chat_messages cmx
        WHERE cmx.session_id = cm.session_id
   )
   AND NOT EXISTS (
       SELECT 1 FROM chat_messages cm2
        WHERE cm2.session_id = cm.session_id
          AND cm2.turn_index = cm.turn_index + 1
   )
`

type FindOrphanedOperatorSessionsRow struct {
	SessionID         pgtype.UUID
	OperatorMessageID pgtype.UUID
	OrphanTurnIndex   int32
}

// M5.2 — orphan-row sweep query (FR-290).
// Detect chat_sessions with status='active' whose newest chat_messages
// row is role='operator', older than the supplied cutoff, with no
// assistant pair at turn_index+1. The boot-time sweep in
// internal/chat/listener.go uses this to detect sessions where the
// supervisor crashed between the operator INSERT and the assistant
// pending row creation; the M5.1 pending-message sweep cannot catch
// these because there's no pending/streaming row to filter on.
func (q *Queries) FindOrphanedOperatorSessions(ctx context.Context, cutoff pgtype.Timestamptz) ([]FindOrphanedOperatorSessionsRow, error) {
	rows, err := q.db.Query(ctx, findOrphanedOperatorSessions, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrphanedOperatorSessionsRow
	for rows.Next() {
		var i FindOrphanedOperatorSessionsRow
		if err := rows.Scan(&i.SessionID, &i.OperatorMessageID, &i.OrphanTurnIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT id, session_id, turn_index, role, status, content, tokens_input, tokens_output, cost_usd, error_kind, raw_event_envelope, created_at, terminated_at FROM chat_messages WHERE id = $1
`

// Listener fast-path lookup: given the message_id from a
// chat.message.sent notify, find the row + its parent session_id
// so the worker can scope its serial mutex.
func (q *Queries) GetChatMessageByID(ctx context.Context, id pgtype.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnIndex,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.TokensInput,
		&i.TokensOutput,
		&i.CostUsd,
		&i.ErrorKind,
		&i.RawEventEnvelope,
		&i.CreatedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, started_by_user_id, started_at, ended_at, status, total_cost_usd, claude_session_label, is_archived FROM chat_sessions WHERE id = $1
`

func (q *Queries) GetChatSession(ctx context.Context, id pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.StartedByUserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TotalCostUsd,
		&i.ClaudeSessionLabel,
		&i.IsArchived,
	)
	return i, err
}

const getMaxTurnIndex = `-- name: GetMaxTurnIndex :one
SELECT COALESCE(MAX(turn_index), -1)::INTEGER AS max_turn_index
  FROM chat_messages
 WHERE session_id = $1
`

// Used by the supervisor when computing the assistant turn_index for
// a fresh INSERT. Returns -1 (via COALESCE) when the session has no
// messages yet.
func (q *Queries) GetMaxTurnIndex(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxTurnIndex, sessionID)
	var max_turn_index int32
	err := row.Scan(&max_turn_index)
	return max_turn_index, err
}

const getSessionTranscript = `-- name: GetSessionTranscript :many
SELECT id, session_id, turn_index, role, status, content, created_at
  FROM chat_messages
 WHERE session_id = $1
   AND (role = 'operator'
        OR (role = 'assistant' AND status = 'completed'))
 ORDER BY turn_index ASC
`

type GetSessionTranscriptRow struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	TurnIndex int32
	Role      string
	Status    string
	Content   *string
	CreatedAt pgtype.Timestamptz
}

// Replay-side query: returns operator rows + completed-assistant rows
// in turn_index order. Failed/aborted assistant rows are excluded
// (clarify Q4 + AssembleTranscript golden fixtures).
func (q *Queries) GetSessionTranscript(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionTranscriptRow, error) {
	rows, err := q.db.Query(ctx, getSessionTranscript, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionTranscriptRow
	for rows.Next() {
		var i GetSessionTranscriptRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAssistantPending = `-- name: InsertAssistantPending :one
INSERT INTO chat_messages (
    id, session_id, turn_index, role, status, created_at
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    'assistant',
    'pending',
    NOW()
)
RETURNING id, session_id, turn_index, role, status, content, tokens_input, tokens_output, cost_usd, error_kind, raw_event_envelope, created_at, terminated_at
`

type InsertAssistantPendingParams struct {
	SessionID pgtype.UUID
	TurnIndex int32
}

// Supervisor-side INSERT of the assistant row at the start of a turn.
// turn_index = the operator turn's turn_index + 1 (caller computes).
func (q *Queries) InsertAssistantPending(ctx context.Context, arg InsertAssistantPendingParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertAssistantPending, arg.SessionID, arg.TurnIndex)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnIndex,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.TokensInput,
		&i.TokensOutput,
		&i.CostUsd,
		&i.ErrorKind,
		&i.RawEventEnvelope,
		&i.CreatedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const insertOperatorMessage = `-- name: InsertOperatorMessage :one
INSERT INTO chat_messages (
    id, session_id, turn_index, role, status, content, created_at
)
VALUES (
    gen_random_uuid(),
    $1,
    COALESCE(
        (SELECT MAX(turn_index) FROM chat_messages WHERE session_id = $1),
        -1
    ) + 1,
    'operator',
    'completed',
    $2,
    NOW()
)
RETURNING id, session_id, turn_index, role, status, content, tokens_input, tokens_output, cost_usd, error_kind, raw_event_envelope, created_at, terminated_at
`

type InsertOperatorMessageParams struct {
	SessionID pgtype.UUID
	Content   *string
}

// Dashboard side INSERTs operator messages directly via Drizzle; the
// supervisor doesn't call this in production (operator messages flow
// through the dashboard server action). Provided for testcontainer
// tests that simulate the dashboard side.
// turn_index is computed inside the same statement: COALESCE(MAX,-1)+1.
func (q *Queries) InsertOperatorMessage(ctx context.Context, arg InsertOperatorMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertOperatorMessage, arg.SessionID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnIndex,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.TokensInput,
		&i.TokensOutput,
		&i.CostUsd,
		&i.ErrorKind,
		&i.RawEventEnvelope,
		&i.CreatedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const insertSyntheticAssistantAborted = `-- name: InsertSyntheticAssistantAborted :exec
INSERT INTO chat_messages (
    id, session_id, turn_index, role, status, content, error_kind, terminated_at
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    'assistant',
    'aborted',
    $3,
    $4,
    NOW()
)
`

type InsertSyntheticAssistantAbortedParams struct {
	SessionID pgtype.UUID
	TurnIndex int32
	Content   *string
	ErrorKind *string
}

// M5.2 — synthesise an aborted assistant row for an orphaned operator
// turn. Used only by the M5.2 orphan-sweep extension at supervisor boot.
// The synthetic row is aborted-from-inception; it never transitions
// through pending/streaming.
func (q *Queries) InsertSyntheticAssistantAborted(ctx context.Context, arg InsertSyntheticAssistantAbortedParams) error {
	_, err := q.db.Exec(ctx, insertSyntheticAssistantAborted,
		arg.SessionID,
		arg.TurnIndex,
		arg.Content,
		arg.ErrorKind,
	)
	return err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, started_by_user_id, started_at, ended_at, status, total_cost_usd, claude_session_label, is_archived FROM chat_sessions
 WHERE started_by_user_id = $1
 ORDER BY started_at DESC
 LIMIT $2
`

type ListSessionsForUserParams struct {
	UserID pgtype.UUID
	Lim    int32
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.StartedByUserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TotalCostUsd,
			&i.ClaudeSessionLabel,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActiveSessionsIdle = `-- name: MarkActiveSessionsIdle :many
UPDATE chat_sessions
   SET status = 'ended', ended_at = NOW()
 WHERE status = 'active'
   AND id NOT IN (
       SELECT DISTINCT session_id
         FROM chat_messages
        WHERE created_at > $1
   )
RETURNING id
`

// Idle-sweep query (FR-081). Marks sessions whose newest chat_messages
// row is older than the supplied cutoff as 'ended' and returns the
// updated session ids so the caller can pg_notify per session.
func (q *Queries) MarkActiveSessionsIdle(ctx context.Context, idleCutoff pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, markActiveSessionsIdle, idleCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingMessagesAborted = `-- name: MarkPendingMessagesAborted :many
UPDATE chat_messages
   SET status        = 'aborted',
       error_kind    = $1,
       terminated_at = NOW()
 WHERE status IN ('pending', 'streaming')
   AND created_at < $2
RETURNING id, session_id
`

type MarkPendingMessagesAbortedParams struct {
	ErrorKind *string
	Cutoff    pgtype.Timestamptz
}

type MarkPendingMessagesAbortedRow struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
}

// Restart-sweep query (FR-083). Marks chat_messages rows in pending or
// streaming state older than the supplied cutoff as aborted with the
// supplied error_kind, and returns the affected ids so the caller can
// terminal-write log lines + roll up the session status.
func (q *Queries) MarkPendingMessagesAborted(ctx context.Context, arg MarkPendingMessagesAbortedParams) ([]MarkPendingMessagesAbortedRow, error) {
	rows, err := q.db.Query(ctx, markPendingMessagesAborted, arg.ErrorKind, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkPendingMessagesAbortedRow
	for rows.Next() {
		var i MarkPendingMessagesAbortedRow
		if err := rows.Scan(&i.ID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionAborted = `-- name: MarkSessionAborted :exec
UPDATE chat_sessions
   SET status = 'aborted', ended_at = NOW()
 WHERE id = $1
   AND status = 'active'
`

// M5.2 — marks a single chat_sessions row aborted. Used by the orphan
// sweep alongside InsertSyntheticAssistantAborted. The existing M5.1
// AbortSessionsWithAbortedMessages query takes a different shape (it
// joins via error_kind across all aborted messages); this is the
// single-row-by-id companion.
func (q *Queries) MarkSessionAborted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSessionAborted, id)
	return err
}

const rollUpSessionCost = `-- name: RollUpSessionCost :exec
UPDATE chat_sessions
   SET total_cost_usd = total_cost_usd + $1
 WHERE id = $2
`

type RollUpSessionCostParams struct {
	DeltaUsd pgtype.Numeric
	ID       pgtype.UUID
}

// Increments total_cost_usd by the assistant turn's cost. Called inside
// the same tx as the assistant chat_messages terminal commit (FR-060).
func (q *Queries) RollUpSessionCost(ctx context.Context, arg RollUpSessionCostParams) error {
	_, err := q.db.Exec(ctx, rollUpSessionCost, arg.DeltaUsd, arg.ID)
	return err
}

const terminalWriteWithError = `-- name: TerminalWriteWithError :exec
UPDATE chat_messages
   SET status = $1, error_kind = $2, terminated_at = NOW()
 WHERE id = $3
`

type TerminalWriteWithErrorParams struct {
	Status    string
	ErrorKind *string
	ID        pgtype.UUID
}

// Used for non-spawn error paths (vault failure, cost-cap reached,
// session ended): writes status + error_kind + terminated_at without
// touching content / cost / envelope. Caller is the chat.Worker before
// a docker container is even started.
func (q *Queries) TerminalWriteWithError(ctx context.Context, arg TerminalWriteWithErrorParams) error {
	_, err := q.db.Exec(ctx, terminalWriteWithError, arg.Status, arg.ErrorKind, arg.ID)
	return err
}

const transitionMessageToStreaming = `-- name: TransitionMessageToStreaming :exec
UPDATE chat_messages
   SET status = 'streaming'
 WHERE id = $1 AND status = 'pending'
`

// ChatPolicy.OnInit calls this once MCP health is verified.
func (q *Queries) TransitionMessageToStreaming(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, transitionMessageToStreaming, id)
	return err
}

const updateChatSessionStatus = `-- name: UpdateChatSessionStatus :exec
UPDATE chat_sessions
   SET status = $1, ended_at = COALESCE(ended_at, NOW())
 WHERE id = $2 AND status = 'active'
`

type UpdateChatSessionStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateChatSessionStatus(ctx context.Context, arg UpdateChatSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateChatSessionStatus, arg.Status, arg.ID)
	return err
}
