// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: departments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, slug, name, concurrency_cap, created_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ConcurrencyCap,
		&i.CreatedAt,
	)
	return i, err
}

const insertDepartment = `-- name: InsertDepartment :one
INSERT INTO departments (slug, name, concurrency_cap)
VALUES ($1, $2, $3)
RETURNING id, slug, name, concurrency_cap, created_at
`

type InsertDepartmentParams struct {
	Slug           string
	Name           string
	ConcurrencyCap int32
}

func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, insertDepartment, arg.Slug, arg.Name, arg.ConcurrencyCap)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ConcurrencyCap,
		&i.CreatedAt,
	)
	return i, err
}
