// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, channel, payload, created_at, processed_at FROM event_outbox WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (EventOutbox, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i EventOutbox
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const lockEventForProcessing = `-- name: LockEventForProcessing :one
SELECT id, channel, payload, created_at, processed_at
FROM event_outbox
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockEventForProcessing(ctx context.Context, id pgtype.UUID) (EventOutbox, error) {
	row := q.db.QueryRow(ctx, lockEventForProcessing, id)
	var i EventOutbox
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE event_outbox
SET processed_at = NOW()
WHERE id = $1 AND processed_at IS NULL
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}

const selectUnprocessedEvents = `-- name: SelectUnprocessedEvents :many
SELECT id, channel, payload, created_at
FROM event_outbox
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT 100
`

type SelectUnprocessedEventsRow struct {
	ID        pgtype.UUID
	Channel   string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SelectUnprocessedEvents(ctx context.Context) ([]SelectUnprocessedEventsRow, error) {
	rows, err := q.db.Query(ctx, selectUnprocessedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUnprocessedEventsRow
	for rows.Next() {
		var i SelectUnprocessedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
