// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: garrisonmutate.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatMutationAuditByID = `-- name: GetChatMutationAuditByID :one
SELECT id, chat_session_id, chat_message_id, verb, args_jsonb, outcome, reversibility_class, affected_resource_id, affected_resource_type, created_at, retention_class FROM chat_mutation_audit WHERE id = $1
`

func (q *Queries) GetChatMutationAuditByID(ctx context.Context, id pgtype.UUID) (ChatMutationAudit, error) {
	row := q.db.QueryRow(ctx, getChatMutationAuditByID, id)
	var i ChatMutationAudit
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.ChatMessageID,
		&i.Verb,
		&i.ArgsJsonb,
		&i.Outcome,
		&i.ReversibilityClass,
		&i.AffectedResourceID,
		&i.AffectedResourceType,
		&i.CreatedAt,
		&i.RetentionClass,
	)
	return i, err
}

const insertChatMutationAudit = `-- name: InsertChatMutationAudit :one

INSERT INTO chat_mutation_audit (
    chat_session_id, chat_message_id, verb, args_jsonb, outcome,
    reversibility_class, affected_resource_id, affected_resource_type
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at
`

type InsertChatMutationAuditParams struct {
	ChatSessionID        pgtype.UUID
	ChatMessageID        pgtype.UUID
	Verb                 string
	ArgsJsonb            []byte
	Outcome              string
	ReversibilityClass   int16
	AffectedResourceID   *string
	AffectedResourceType *string
}

type InsertChatMutationAuditRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M5.3 chat-driven mutation audit queries.
// Used by supervisor/internal/garrisonmutate/audit.go for write-side
// and by integration tests + (eventually) operator-side forensic
// surfaces for read-side. The dashboard's read-only access is via the
// garrison_dashboard_app role's SELECT grant from the M5.3 migration.
// Records every garrison-mutate verb call (success or failure). For
// success rows, runs in the same transaction as the data write. For
// failure rows, runs in a separate audit-only transaction (the
// data-side ROLLBACK invalidates a same-tx audit INSERT). args_jsonb
// captures the full args including operator-typed text passed via the
// chat (Rule 6 backstop applies to PG_NOTIFY payloads, NOT to this
// table — chat-content text in args_jsonb is forensically required).
func (q *Queries) InsertChatMutationAudit(ctx context.Context, arg InsertChatMutationAuditParams) (InsertChatMutationAuditRow, error) {
	row := q.db.QueryRow(ctx, insertChatMutationAudit,
		arg.ChatSessionID,
		arg.ChatMessageID,
		arg.Verb,
		arg.ArgsJsonb,
		arg.Outcome,
		arg.ReversibilityClass,
		arg.AffectedResourceID,
		arg.AffectedResourceType,
	)
	var i InsertChatMutationAuditRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listChatMutationAuditForSession = `-- name: ListChatMutationAuditForSession :many
SELECT id, chat_session_id, chat_message_id, verb, args_jsonb, outcome, reversibility_class, affected_resource_id, affected_resource_type, created_at, retention_class FROM chat_mutation_audit
WHERE chat_session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListChatMutationAuditForSessionParams struct {
	ChatSessionID pgtype.UUID
	Limit         int32
}

func (q *Queries) ListChatMutationAuditForSession(ctx context.Context, arg ListChatMutationAuditForSessionParams) ([]ChatMutationAudit, error) {
	rows, err := q.db.Query(ctx, listChatMutationAuditForSession, arg.ChatSessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMutationAudit
	for rows.Next() {
		var i ChatMutationAudit
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.ChatMessageID,
			&i.Verb,
			&i.ArgsJsonb,
			&i.Outcome,
			&i.ReversibilityClass,
			&i.AffectedResourceID,
			&i.AffectedResourceType,
			&i.CreatedAt,
			&i.RetentionClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
