// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hiring.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHiringProposalByID = `-- name: GetHiringProposalByID :one
SELECT id, role_title, department_slug, justification_md, skills_summary_md, proposed_via, proposed_by_chat_session_id, status, created_at FROM hiring_proposals WHERE id = $1
`

func (q *Queries) GetHiringProposalByID(ctx context.Context, id pgtype.UUID) (HiringProposal, error) {
	row := q.db.QueryRow(ctx, getHiringProposalByID, id)
	var i HiringProposal
	err := row.Scan(
		&i.ID,
		&i.RoleTitle,
		&i.DepartmentSlug,
		&i.JustificationMd,
		&i.SkillsSummaryMd,
		&i.ProposedVia,
		&i.ProposedByChatSessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertHiringProposal = `-- name: InsertHiringProposal :one

INSERT INTO hiring_proposals (
    role_title, department_slug, justification_md, skills_summary_md,
    proposed_via, proposed_by_chat_session_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, status
`

type InsertHiringProposalParams struct {
	RoleTitle               string
	DepartmentSlug          string
	JustificationMd         string
	SkillsSummaryMd         *string
	ProposedVia             string
	ProposedByChatSessionID pgtype.UUID
}

type InsertHiringProposalRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Status    string
}

// M5.3 hiring_proposals queries.
// Used by supervisor/internal/garrisonmutate/verbs_hiring.go for the
// propose_hire verb's INSERT path, and by the dashboard's stopgap
// /hiring/proposals page for the read-side. Dashboard-side reads via
// Drizzle directly; supervisor-side writes via these sqlc queries.
// Used by garrison-mutate.propose_hire. Always sets proposed_via to
// 'ceo_chat' and proposed_by_chat_session_id when invoked from the
// chat verb path. M7's dashboard-side proposal action will use this
// same query with proposed_via='dashboard' and a NULL chat_session_id.
func (q *Queries) InsertHiringProposal(ctx context.Context, arg InsertHiringProposalParams) (InsertHiringProposalRow, error) {
	row := q.db.QueryRow(ctx, insertHiringProposal,
		arg.RoleTitle,
		arg.DepartmentSlug,
		arg.JustificationMd,
		arg.SkillsSummaryMd,
		arg.ProposedVia,
		arg.ProposedByChatSessionID,
	)
	var i InsertHiringProposalRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Status)
	return i, err
}

const listHiringProposals = `-- name: ListHiringProposals :many
SELECT id, role_title, department_slug, justification_md, skills_summary_md, proposed_via, proposed_by_chat_session_id, status, created_at FROM hiring_proposals
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListHiringProposals(ctx context.Context, limit int32) ([]HiringProposal, error) {
	rows, err := q.db.Query(ctx, listHiringProposals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HiringProposal
	for rows.Next() {
		var i HiringProposal
		if err := rows.Scan(
			&i.ID,
			&i.RoleTitle,
			&i.DepartmentSlug,
			&i.JustificationMd,
			&i.SkillsSummaryMd,
			&i.ProposedVia,
			&i.ProposedByChatSessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiringProposalsByStatus = `-- name: ListHiringProposalsByStatus :many
SELECT id, role_title, department_slug, justification_md, skills_summary_md, proposed_via, proposed_by_chat_session_id, status, created_at FROM hiring_proposals
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListHiringProposalsByStatusParams struct {
	Status string
	Limit  int32
}

func (q *Queries) ListHiringProposalsByStatus(ctx context.Context, arg ListHiringProposalsByStatusParams) ([]HiringProposal, error) {
	rows, err := q.db.Query(ctx, listHiringProposalsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HiringProposal
	for rows.Next() {
		var i HiringProposal
		if err := rows.Scan(
			&i.ID,
			&i.RoleTitle,
			&i.DepartmentSlug,
			&i.JustificationMd,
			&i.SkillsSummaryMd,
			&i.ProposedVia,
			&i.ProposedByChatSessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
