// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m11_action_broker.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDispatchablePendingAction = `-- name: ClaimDispatchablePendingAction :one
SELECT id, action_type, target, rendered_payload, agent_instance_id, ticket_id,
       tier, tier_reason, status, approved_by, dispatched_at, created_at
  FROM pending_actions
 WHERE status IN ('pending', 'approved')
   AND tier <> 'human_only'
 ORDER BY created_at
   FOR UPDATE SKIP LOCKED
 LIMIT 1
`

// Dispatcher claim (FR-021). FOR UPDATE SKIP LOCKED gives each dispatchable
// row at most one claimant regardless of concurrent dispatcher instances.
// The partial index idx_pending_actions_dispatchable serves exactly this
// predicate (status IN ('pending','approved') AND tier <> 'human_only').
// LIMIT 1 bounds the claim to one row per Handle call.
// human_only rows are structurally excluded by the index predicate so they
// are never claimed through the normal LISTEN path.
func (q *Queries) ClaimDispatchablePendingAction(ctx context.Context) (PendingAction, error) {
	row := q.db.QueryRow(ctx, claimDispatchablePendingAction)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.Target,
		&i.RenderedPayload,
		&i.AgentInstanceID,
		&i.TicketID,
		&i.Tier,
		&i.TierReason,
		&i.Status,
		&i.ApprovedBy,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingActionByID = `-- name: GetPendingActionByID :one
SELECT id, action_type, target, rendered_payload, agent_instance_id, ticket_id,
       tier, tier_reason, status, approved_by, dispatched_at, created_at
  FROM pending_actions
 WHERE id = $1::uuid
`

// Single-row re-read for the dispatcher's Handle implementation: after
// claiming a row via FOR UPDATE SKIP LOCKED, the dispatcher re-reads it
// to confirm the status is still in the dispatchable set (a row may
// transition between the LISTEN notify and the claim — the restart-mid-
// dispatch guard SC-006).
func (q *Queries) GetPendingActionByID(ctx context.Context, id pgtype.UUID) (PendingAction, error) {
	row := q.db.QueryRow(ctx, getPendingActionByID, id)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.Target,
		&i.RenderedPayload,
		&i.AgentInstanceID,
		&i.TicketID,
		&i.Tier,
		&i.TierReason,
		&i.Status,
		&i.ApprovedBy,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPendingAction = `-- name: InsertPendingAction :one

INSERT INTO pending_actions (
    action_type,
    target,
    rendered_payload,
    agent_instance_id,
    ticket_id,
    tier,
    tier_reason
) VALUES (
    $1::text,
    $2::jsonb,
    $3::text,
    $4::uuid,
    $5::uuid,
    $6::text,
    $7::text
)
RETURNING id, tier
`

type InsertPendingActionParams struct {
	ActionType      string
	Target          []byte
	RenderedPayload string
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	Tier            string
	TierReason      string
}

type InsertPendingActionRow struct {
	ID   pgtype.UUID
	Tier string
}

// M11 action-broker queries (plan §sqlc).
// Used by:
//   - supervisor/internal/garrisonmutate/verbs_actions.go (request_external_action verb:
//     InsertPendingAction + InsertPendingActionOutcome in one transaction).
//   - supervisor/internal/actionbroker/dispatcher.go (dispatcher worker: claim,
//     mark executed/failed, outcome writes).
//   - supervisor/internal/actionbroker/... (GetPendingActionByID for re-read;
//     ListPendingApproveActions + ListPendingActionOutcomes for dashboard API).
//
// All parameters use sqlc.arg(name) exclusively (M7 retro gotcha).
// Writes the immutable pending-action row at verb call time (FR-003).
// The tier is policy-table-assigned by the caller (never agent-supplied);
// the DB-level pending_actions_floor_is_approve CHECK provides the third
// enforcement layer (plan D5c). Returns id and tier so the verb handler
// can include them in the Result message (FR-004).
func (q *Queries) InsertPendingAction(ctx context.Context, arg InsertPendingActionParams) (InsertPendingActionRow, error) {
	row := q.db.QueryRow(ctx, insertPendingAction,
		arg.ActionType,
		arg.Target,
		arg.RenderedPayload,
		arg.AgentInstanceID,
		arg.TicketID,
		arg.Tier,
		arg.TierReason,
	)
	var i InsertPendingActionRow
	err := row.Scan(&i.ID, &i.Tier)
	return i, err
}

const insertPendingActionOutcome = `-- name: InsertPendingActionOutcome :exec
INSERT INTO pending_action_outcomes (
    pending_action_id,
    agent_instance_id,
    outcome,
    detail,
    structured_outcome
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::jsonb
)
`

type InsertPendingActionOutcomeParams struct {
	PendingActionID   pgtype.UUID
	AgentInstanceID   pgtype.UUID
	Outcome           string
	Detail            string
	StructuredOutcome []byte
}

// Appends one immutable outcome row to the action's history (FR-024).
// Mirrors M9's scheduled_task_runs append shape: the request row is not
// mutated in place beyond status transitions; outcomes are appended here.
func (q *Queries) InsertPendingActionOutcome(ctx context.Context, arg InsertPendingActionOutcomeParams) error {
	_, err := q.db.Exec(ctx, insertPendingActionOutcome,
		arg.PendingActionID,
		arg.AgentInstanceID,
		arg.Outcome,
		arg.Detail,
		arg.StructuredOutcome,
	)
	return err
}

const listPendingActionOutcomes = `-- name: ListPendingActionOutcomes :many
SELECT id, pending_action_id, agent_instance_id, outcome, detail,
       structured_outcome, created_at
  FROM pending_action_outcomes
 WHERE pending_action_id = $1::uuid
 ORDER BY created_at
`

// Full outcome history for a pending_actions row (FR-007, SC-007).
// Used to reconstruct the audit trail: requested → approved/rejected →
// executed/failed/done/skipped_human_only. Ordered by created_at so the
// timeline is in arrival order.
func (q *Queries) ListPendingActionOutcomes(ctx context.Context, pendingActionID pgtype.UUID) ([]PendingActionOutcome, error) {
	rows, err := q.db.Query(ctx, listPendingActionOutcomes, pendingActionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingActionOutcome
	for rows.Next() {
		var i PendingActionOutcome
		if err := rows.Scan(
			&i.ID,
			&i.PendingActionID,
			&i.AgentInstanceID,
			&i.Outcome,
			&i.Detail,
			&i.StructuredOutcome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApproveActions = `-- name: ListPendingApproveActions :many
SELECT id, action_type, target, rendered_payload, agent_instance_id, ticket_id,
       tier, tier_reason, status, approved_by, dispatched_at, created_at
  FROM pending_actions
 WHERE tier = 'approve'
   AND status = 'pending'
 ORDER BY created_at
`

// Outbox approval-queue read (FR-025): approve-tier rows still at
// status='pending' (awaiting the operator's approve/reject click).
// Ordered oldest-first so the operator sees the queue in arrival order.
func (q *Queries) ListPendingApproveActions(ctx context.Context) ([]PendingAction, error) {
	rows, err := q.db.Query(ctx, listPendingApproveActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAction
	for rows.Next() {
		var i PendingAction
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Target,
			&i.RenderedPayload,
			&i.AgentInstanceID,
			&i.TicketID,
			&i.Tier,
			&i.TierReason,
			&i.Status,
			&i.ApprovedBy,
			&i.DispatchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingActionExecuted = `-- name: MarkPendingActionExecuted :exec
UPDATE pending_actions
   SET status       = 'executed',
       dispatched_at = $1::timestamptz
 WHERE id = $2::uuid
`

type MarkPendingActionExecutedParams struct {
	DispatchedAt pgtype.Timestamptz
	ID           pgtype.UUID
}

// Terminal success transition: status → executed, dispatched_at set (FR-021,
// FR-024). Called after the external provider POST returns 2xx. Together with
// the FOR UPDATE SKIP LOCKED claim this provides the exactly-once guarantee —
// a re-claimed row in 'executed' status is a no-op (terminal state).
func (q *Queries) MarkPendingActionExecuted(ctx context.Context, arg MarkPendingActionExecutedParams) error {
	_, err := q.db.Exec(ctx, markPendingActionExecuted, arg.DispatchedAt, arg.ID)
	return err
}

const markPendingActionFailed = `-- name: MarkPendingActionFailed :exec
UPDATE pending_actions
   SET status = 'failed'
 WHERE id = $1::uuid
`

// Terminal failure transition: status → failed (FR-022). Called when the
// external provider returns a non-recoverable error or vault is unavailable
// (FR-023). No auto-retry in M11 alpha; the row surfaces in the Outbox for
// operator-initiated re-request.
func (q *Queries) MarkPendingActionFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPendingActionFailed, id)
	return err
}
