// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m7_1_agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAgentsForContainerReconcile = `-- name: ListAgentsForContainerReconcile :many

SELECT id, role_slug, host_uid, image_digest
FROM agents
WHERE host_uid IS NOT NULL
ORDER BY role_slug
`

type ListAgentsForContainerReconcileRow struct {
	ID          pgtype.UUID
	RoleSlug    string
	HostUid     *int32
	ImageDigest *string
}

// M7.1 agent queries.
// Boot-time container shape reconcile (plan §9): cmd/supervisor lists
// every agent that owns a per-agent container, builds the desired
// ContainerSpec for each, and hands the set to ReconcileShape.
// host_uid IS NOT NULL covers grandfathered AND hired agents — hired
// agents never receive last_grandfathered_at (analyze C1), but both
// populations get a host_uid when their container is provisioned.
// ORDER BY keeps reconcile logs and tests deterministic.
func (q *Queries) ListAgentsForContainerReconcile(ctx context.Context) ([]ListAgentsForContainerReconcileRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForContainerReconcile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsForContainerReconcileRow
	for rows.Next() {
		var i ListAgentsForContainerReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleSlug,
			&i.HostUid,
			&i.ImageDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
