// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m7_hiring.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveProposal = `-- name: ApproveProposal :exec
UPDATE hiring_proposals
SET status = 'approved', approved_at = NOW(), approved_by = $1
WHERE id = $2 AND status = 'pending'
`

type ApproveProposalParams struct {
	ApprovedBy pgtype.UUID
	ID         pgtype.UUID
}

// Server-Action approve write. Status moves pending -> approved (or
// pending -> install_in_progress for proposals that queue an install
// atomically; second UPDATE is the caller's responsibility).
func (q *Queries) ApproveProposal(ctx context.Context, arg ApproveProposalParams) error {
	_, err := q.db.Exec(ctx, approveProposal, arg.ApprovedBy, arg.ID)
	return err
}

const insertHiringProposalM7 = `-- name: InsertHiringProposalM7 :one

INSERT INTO hiring_proposals (
    role_title, department_slug, justification_md, skills_summary_md,
    proposed_via, proposed_by_chat_session_id,
    target_agent_id, proposal_type,
    skill_diff_jsonb, proposal_snapshot_jsonb, skill_digest_at_propose
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, status, proposal_type
`

type InsertHiringProposalM7Params struct {
	RoleTitle               string
	DepartmentSlug          string
	JustificationMd         string
	SkillsSummaryMd         *string
	ProposedVia             string
	ProposedByChatSessionID pgtype.UUID
	TargetAgentID           pgtype.UUID
	ProposalType            string
	SkillDiffJsonb          []byte
	ProposalSnapshotJsonb   []byte
	SkillDigestAtPropose    *string
}

type InsertHiringProposalM7Row struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	Status       string
	ProposalType string
}

// M7 hiring queries.
// Extends the M5.3 hiring_proposals surface with M7 columns (target_agent_id,
// proposal_type, skill_diff_jsonb, proposal_snapshot_jsonb, skill_digest_at_propose,
// approval/rejection metadata, install lifecycle states). Used by:
//   - supervisor/internal/garrisonmutate/verbs_hiring.go (propose_skill_change,
//     bump_skill_version chat verbs)
//   - supervisor/internal/garrisonmutate/approve.go (Server-Action helpers)
//   - dashboard /admin/hires reads via Drizzle directly.
//
// Variant of InsertHiringProposal carrying the M7 fields. Used by
// propose_skill_change + bump_skill_version. proposal_type is
// explicit; target_agent_id required for skill_change/version_bump.
func (q *Queries) InsertHiringProposalM7(ctx context.Context, arg InsertHiringProposalM7Params) (InsertHiringProposalM7Row, error) {
	row := q.db.QueryRow(ctx, insertHiringProposalM7,
		arg.RoleTitle,
		arg.DepartmentSlug,
		arg.JustificationMd,
		arg.SkillsSummaryMd,
		arg.ProposedVia,
		arg.ProposedByChatSessionID,
		arg.TargetAgentID,
		arg.ProposalType,
		arg.SkillDiffJsonb,
		arg.ProposalSnapshotJsonb,
		arg.SkillDigestAtPropose,
	)
	var i InsertHiringProposalM7Row
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.ProposalType,
	)
	return i, err
}

const listInstallInProgressProposals = `-- name: ListInstallInProgressProposals :many
SELECT id, role_title, department_slug, justification_md, skills_summary_md, proposed_via, proposed_by_chat_session_id, status, created_at, target_agent_id, proposal_type, skill_diff_jsonb, proposal_snapshot_jsonb, skill_digest_at_propose, approved_at, approved_by, rejected_at, rejected_reason FROM hiring_proposals
WHERE status = 'install_in_progress'
ORDER BY approved_at ASC
`

// Read at supervisor restart by skillinstall.recover so the install
// pipeline can resume each in-flight install from its journal.
func (q *Queries) ListInstallInProgressProposals(ctx context.Context) ([]HiringProposal, error) {
	rows, err := q.db.Query(ctx, listInstallInProgressProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HiringProposal
	for rows.Next() {
		var i HiringProposal
		if err := rows.Scan(
			&i.ID,
			&i.RoleTitle,
			&i.DepartmentSlug,
			&i.JustificationMd,
			&i.SkillsSummaryMd,
			&i.ProposedVia,
			&i.ProposedByChatSessionID,
			&i.Status,
			&i.CreatedAt,
			&i.TargetAgentID,
			&i.ProposalType,
			&i.SkillDiffJsonb,
			&i.ProposalSnapshotJsonb,
			&i.SkillDigestAtPropose,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.RejectedAt,
			&i.RejectedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProposalsByTargetAgent = `-- name: ListPendingProposalsByTargetAgent :many
SELECT id, role_title, department_slug, justification_md, skills_summary_md, proposed_via, proposed_by_chat_session_id, status, created_at, target_agent_id, proposal_type, skill_diff_jsonb, proposal_snapshot_jsonb, skill_digest_at_propose, approved_at, approved_by, rejected_at, rejected_reason FROM hiring_proposals
WHERE status = 'pending'
  AND target_agent_id = $1
ORDER BY created_at DESC
`

// FR-109 sibling-proposal display: pending proposals targeting the
// same agent (so the operator can pick which one they meant).
func (q *Queries) ListPendingProposalsByTargetAgent(ctx context.Context, targetAgentID pgtype.UUID) ([]HiringProposal, error) {
	rows, err := q.db.Query(ctx, listPendingProposalsByTargetAgent, targetAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HiringProposal
	for rows.Next() {
		var i HiringProposal
		if err := rows.Scan(
			&i.ID,
			&i.RoleTitle,
			&i.DepartmentSlug,
			&i.JustificationMd,
			&i.SkillsSummaryMd,
			&i.ProposedVia,
			&i.ProposedByChatSessionID,
			&i.Status,
			&i.CreatedAt,
			&i.TargetAgentID,
			&i.ProposalType,
			&i.SkillDiffJsonb,
			&i.ProposalSnapshotJsonb,
			&i.SkillDigestAtPropose,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.RejectedAt,
			&i.RejectedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallFailed = `-- name: MarkInstallFailed :exec
UPDATE hiring_proposals
SET status = 'install_failed', rejected_reason = $1
WHERE id = $2 AND status IN ('install_in_progress', 'approved')
`

type MarkInstallFailedParams struct {
	RejectedReason *string
	ID             pgtype.UUID
}

func (q *Queries) MarkInstallFailed(ctx context.Context, arg MarkInstallFailedParams) error {
	_, err := q.db.Exec(ctx, markInstallFailed, arg.RejectedReason, arg.ID)
	return err
}

const markInstalled = `-- name: MarkInstalled :exec
UPDATE hiring_proposals
SET status = 'installed'
WHERE id = $1 AND status = 'install_in_progress'
`

func (q *Queries) MarkInstalled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInstalled, id)
	return err
}

const rejectProposal = `-- name: RejectProposal :exec
UPDATE hiring_proposals
SET status = 'rejected', rejected_at = NOW(), rejected_reason = $1
WHERE id = $2 AND status = 'pending'
`

type RejectProposalParams struct {
	RejectedReason *string
	ID             pgtype.UUID
}

func (q *Queries) RejectProposal(ctx context.Context, arg RejectProposalParams) error {
	_, err := q.db.Exec(ctx, rejectProposal, arg.RejectedReason, arg.ID)
	return err
}

const supersedeSiblingProposals = `-- name: SupersedeSiblingProposals :execrows
UPDATE hiring_proposals
SET status = 'superseded',
    rejected_at = NOW(),
    rejected_reason = 'superseded_by:' || $1::text
WHERE status = 'pending'
  AND target_agent_id = $2
  AND proposal_type = $3
  AND id != $4
`

type SupersedeSiblingProposalsParams struct {
	Column1       string
	TargetAgentID pgtype.UUID
	ProposalType  string
	ID            pgtype.UUID
}

// FR-110a: when one proposal is approved, sibling pending proposals
// targeting the same (agent, package, type) auto-reject. Returns
// the count of rows superseded so the audit row can record it.
func (q *Queries) SupersedeSiblingProposals(ctx context.Context, arg SupersedeSiblingProposalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeSiblingProposals,
		arg.Column1,
		arg.TargetAgentID,
		arg.ProposalType,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionToInstallInProgress = `-- name: TransitionToInstallInProgress :exec
UPDATE hiring_proposals
SET status = 'install_in_progress'
WHERE id = $1 AND status = 'approved'
`

// Called inside the same Server-Action tx as ApproveProposal so the
// skillinstall.Actuator can pick up the proposal from a single
// consistent state.
func (q *Queries) TransitionToInstallInProgress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, transitionToInstallInProgress, id)
	return err
}
