// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m7_install_journal.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSuccessfulStepsForProposal = `-- name: CountSuccessfulStepsForProposal :one
SELECT COUNT(*) AS n
FROM agent_install_journal
WHERE proposal_id = $1
  AND outcome = 'success'
`

// Cheap read used by Resume to short-circuit when all 6 steps are
// already success.
func (q *Queries) CountSuccessfulStepsForProposal(ctx context.Context, proposalID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulStepsForProposal, proposalID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const getLatestInstallStep = `-- name: GetLatestInstallStep :one
SELECT id, proposal_id, step, outcome, error_kind, payload_jsonb, created_at FROM agent_install_journal
WHERE proposal_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Read at supervisor restart by skillinstall.Resume to determine
// where to pick up. Returns the most recent step regardless of
// outcome; the resumer interprets:
//   - outcome='success' on the last step in the pipeline -> done
//   - outcome='success' on intermediate step -> resume from next step
//   - outcome='failed' -> install_failed terminal
//   - outcome='interrupted' -> recover detected supervisor crash mid-step
func (q *Queries) GetLatestInstallStep(ctx context.Context, proposalID pgtype.UUID) (AgentInstallJournal, error) {
	row := q.db.QueryRow(ctx, getLatestInstallStep, proposalID)
	var i AgentInstallJournal
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.Step,
		&i.Outcome,
		&i.ErrorKind,
		&i.PayloadJsonb,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstallStep = `-- name: InsertInstallStep :one

INSERT INTO agent_install_journal (
    proposal_id, step, outcome, error_kind, payload_jsonb
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertInstallStepParams struct {
	ProposalID   pgtype.UUID
	Step         string
	Outcome      string
	ErrorKind    *string
	PayloadJsonb []byte
}

type InsertInstallStepRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M7 install journal queries.
// Used by supervisor/internal/skillinstall/journal.go (writes per step)
// and supervisor/internal/skillinstall/recover.go (resume-or-rollback
// on supervisor restart). Per-step audit is the M5.3 chat_mutation_audit
// analogue scoped to install pipeline steps; see migration §"Schema
// deviation from spec FR-214a" for the rationale.
// One row per material install step. Outcome captured at the step's
// terminal event; pre-step rows OMIT outcome (NULL via the helper
// pattern below) so an interrupted step can be detected by recovery
// as "row exists with no terminal outcome".
func (q *Queries) InsertInstallStep(ctx context.Context, arg InsertInstallStepParams) (InsertInstallStepRow, error) {
	row := q.db.QueryRow(ctx, insertInstallStep,
		arg.ProposalID,
		arg.Step,
		arg.Outcome,
		arg.ErrorKind,
		arg.PayloadJsonb,
	)
	var i InsertInstallStepRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listInstallStepsForProposal = `-- name: ListInstallStepsForProposal :many
SELECT id, proposal_id, step, outcome, error_kind, payload_jsonb, created_at FROM agent_install_journal
WHERE proposal_id = $1
ORDER BY created_at ASC
`

// Forensic-query view (FR-111). Returns every step row for a proposal
// in chronological order so the operator can see the full install
// history.
func (q *Queries) ListInstallStepsForProposal(ctx context.Context, proposalID pgtype.UUID) ([]AgentInstallJournal, error) {
	rows, err := q.db.Query(ctx, listInstallStepsForProposal, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstallJournal
	for rows.Next() {
		var i AgentInstallJournal
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.Step,
			&i.Outcome,
			&i.ErrorKind,
			&i.PayloadJsonb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterruptedSteps = `-- name: MarkInterruptedSteps :execrows
UPDATE agent_install_journal aij
SET outcome = 'interrupted'
FROM hiring_proposals hp
WHERE aij.proposal_id = hp.id
  AND hp.status = 'install_in_progress'
  AND aij.outcome NOT IN ('success', 'failed', 'interrupted')
  AND aij.id IN (
      SELECT id FROM agent_install_journal
      WHERE proposal_id = aij.proposal_id
      ORDER BY created_at DESC
      LIMIT 1
  )
`

// Called once at supervisor startup, before the per-proposal Resume
// pass. Any step row that lacks a terminal outcome AND whose proposal
// is install_in_progress is marked 'interrupted' so subsequent reads
// see the unambiguous state. Returns the count of rows touched.
func (q *Queries) MarkInterruptedSteps(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markInterruptedSteps)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
