// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m7_runtime.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateNextHostUID = `-- name: AllocateNextHostUID :one
SELECT COALESCE(MAX(host_uid), $1::int - 1) + 1 AS next_uid
FROM agents
WHERE host_uid >= $1::int AND host_uid <= $2::int
`

type AllocateNextHostUIDParams struct {
	Column1 int32
	Column2 int32
}

// FR-206a sequential allocator. Returns MAX(host_uid)+1 within the
// per-customer range; if no rows exist in range, returns range start.
// Caller guards against ceiling-exhaustion (returned value > range_end).
func (q *Queries) AllocateNextHostUID(ctx context.Context, arg AllocateNextHostUIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, allocateNextHostUID, arg.Column1, arg.Column2)
	var next_uid int32
	err := row.Scan(&next_uid)
	return next_uid, err
}

const getLatestContainerEventForAgent = `-- name: GetLatestContainerEventForAgent :one
SELECT id, agent_id, kind, image_digest, started_at, stopped_at, stop_reason, cgroup_caps_jsonb, retention_class, created_at FROM agent_container_events
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestContainerEventForAgent(ctx context.Context, agentID pgtype.UUID) (AgentContainerEvent, error) {
	row := q.db.QueryRow(ctx, getLatestContainerEventForAgent, agentID)
	var i AgentContainerEvent
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Kind,
		&i.ImageDigest,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.CgroupCapsJsonb,
		&i.RetentionClass,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentContainerEvent = `-- name: InsertAgentContainerEvent :one

INSERT INTO agent_container_events (
    agent_id, kind, image_digest, started_at, stopped_at,
    stop_reason, cgroup_caps_jsonb, retention_class
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at
`

type InsertAgentContainerEventParams struct {
	AgentID         pgtype.UUID
	Kind            string
	ImageDigest     *string
	StartedAt       pgtype.Timestamptz
	StoppedAt       pgtype.Timestamptz
	StopReason      *string
	CgroupCapsJsonb []byte
	RetentionClass  *string
}

type InsertAgentContainerEventRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M7 per-agent runtime queries.
// agent_container_events writes + reads, host_uid allocator,
// agents extension columns. Used by:
//   - supervisor/internal/agentcontainer/socketproxy.go (lifecycle events)
//   - supervisor/internal/agentcontainer/reconcile.go (restart adoption)
//   - supervisor/internal/migrate7/run.go (grandfathering migration)
//   - supervisor/internal/garrisonmutate/approve.go (post-approval activation).
func (q *Queries) InsertAgentContainerEvent(ctx context.Context, arg InsertAgentContainerEventParams) (InsertAgentContainerEventRow, error) {
	row := q.db.QueryRow(ctx, insertAgentContainerEvent,
		arg.AgentID,
		arg.Kind,
		arg.ImageDigest,
		arg.StartedAt,
		arg.StoppedAt,
		arg.StopReason,
		arg.CgroupCapsJsonb,
		arg.RetentionClass,
	)
	var i InsertAgentContainerEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listActiveAgentsWithContainerState = `-- name: ListActiveAgentsWithContainerState :many
SELECT
    a.id AS agent_id,
    a.image_digest,
    a.host_uid,
    a.last_grandfathered_at,
    e.kind AS last_event_kind,
    e.created_at AS last_event_at
FROM agents a
LEFT JOIN LATERAL (
    SELECT kind, created_at
    FROM agent_container_events
    WHERE agent_id = a.id
    ORDER BY created_at DESC
    LIMIT 1
) e ON true
WHERE a.status = 'active'
`

type ListActiveAgentsWithContainerStateRow struct {
	AgentID             pgtype.UUID
	ImageDigest         *string
	HostUid             *int32
	LastGrandfatheredAt pgtype.Timestamptz
	LastEventKind       string
	LastEventAt         pgtype.Timestamptz
}

// Read by agentcontainer.Reconcile at supervisor restart. Joins each
// active agent with its most recent container event so the reconciler
// can compare against `docker ps`.
func (q *Queries) ListActiveAgentsWithContainerState(ctx context.Context) ([]ListActiveAgentsWithContainerStateRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentsWithContainerState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAgentsWithContainerStateRow
	for rows.Next() {
		var i ListActiveAgentsWithContainerStateRow
		if err := rows.Scan(
			&i.AgentID,
			&i.ImageDigest,
			&i.HostUid,
			&i.LastGrandfatheredAt,
			&i.LastEventKind,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsNotGrandfathered = `-- name: ListAgentsNotGrandfathered :many
SELECT id, department_id, role_slug, agent_md, model, skills, mcp_tools, listens_for, palace_wing, status, created_at, mcp_config, updated_at, image_digest, runtime_caps, egress_grant_jsonb, mcp_servers_jsonb, last_grandfathered_at, host_uid FROM agents
WHERE last_grandfathered_at IS NULL
ORDER BY created_at ASC
`

// Read at supervisor startup by migrate7.Run; agents with NULL
// last_grandfathered_at are M2.x-seeded and need the M7 cutover.
func (q *Queries) ListAgentsNotGrandfathered(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsNotGrandfathered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.RoleSlug,
			&i.AgentMd,
			&i.Model,
			&i.Skills,
			&i.McpTools,
			&i.ListensFor,
			&i.PalaceWing,
			&i.Status,
			&i.CreatedAt,
			&i.McpConfig,
			&i.UpdatedAt,
			&i.ImageDigest,
			&i.RuntimeCaps,
			&i.EgressGrantJsonb,
			&i.McpServersJsonb,
			&i.LastGrandfatheredAt,
			&i.HostUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainerEventsByAgent = `-- name: ListContainerEventsByAgent :many
SELECT id, agent_id, kind, image_digest, started_at, stopped_at, stop_reason, cgroup_caps_jsonb, retention_class, created_at FROM agent_container_events
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListContainerEventsByAgentParams struct {
	AgentID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListContainerEventsByAgent(ctx context.Context, arg ListContainerEventsByAgentParams) ([]AgentContainerEvent, error) {
	rows, err := q.db.Query(ctx, listContainerEventsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentContainerEvent
	for rows.Next() {
		var i AgentContainerEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.ImageDigest,
			&i.StartedAt,
			&i.StoppedAt,
			&i.StopReason,
			&i.CgroupCapsJsonb,
			&i.RetentionClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainerEventsByKind = `-- name: ListContainerEventsByKind :many
SELECT id, agent_id, kind, image_digest, started_at, stopped_at, stop_reason, cgroup_caps_jsonb, retention_class, created_at FROM agent_container_events
WHERE kind = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListContainerEventsByKindParams struct {
	Kind  string
	Limit int32
}

func (q *Queries) ListContainerEventsByKind(ctx context.Context, arg ListContainerEventsByKindParams) ([]AgentContainerEvent, error) {
	rows, err := q.db.Query(ctx, listContainerEventsByKind, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentContainerEvent
	for rows.Next() {
		var i AgentContainerEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.ImageDigest,
			&i.StartedAt,
			&i.StoppedAt,
			&i.StopReason,
			&i.CgroupCapsJsonb,
			&i.RetentionClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentEgressGrants = `-- name: SetAgentEgressGrants :exec
UPDATE agents
SET egress_grant_jsonb = $1
WHERE id = $2
`

type SetAgentEgressGrantsParams struct {
	EgressGrantJsonb []byte
	ID               pgtype.UUID
}

func (q *Queries) SetAgentEgressGrants(ctx context.Context, arg SetAgentEgressGrantsParams) error {
	_, err := q.db.Exec(ctx, setAgentEgressGrants, arg.EgressGrantJsonb, arg.ID)
	return err
}

const setAgentHostUID = `-- name: SetAgentHostUID :exec
UPDATE agents
SET host_uid = $1
WHERE id = $2
`

type SetAgentHostUIDParams struct {
	HostUid *int32
	ID      pgtype.UUID
}

func (q *Queries) SetAgentHostUID(ctx context.Context, arg SetAgentHostUIDParams) error {
	_, err := q.db.Exec(ctx, setAgentHostUID, arg.HostUid, arg.ID)
	return err
}

const setAgentImageDigest = `-- name: SetAgentImageDigest :exec
UPDATE agents
SET image_digest = $1
WHERE id = $2
`

type SetAgentImageDigestParams struct {
	ImageDigest *string
	ID          pgtype.UUID
}

func (q *Queries) SetAgentImageDigest(ctx context.Context, arg SetAgentImageDigestParams) error {
	_, err := q.db.Exec(ctx, setAgentImageDigest, arg.ImageDigest, arg.ID)
	return err
}

const setAgentLastGrandfathered = `-- name: SetAgentLastGrandfathered :exec
UPDATE agents
SET last_grandfathered_at = NOW(),
    image_digest = $1,
    host_uid = $2
WHERE id = $3 AND last_grandfathered_at IS NULL
`

type SetAgentLastGrandfatheredParams struct {
	ImageDigest *string
	HostUid     *int32
	ID          pgtype.UUID
}

func (q *Queries) SetAgentLastGrandfathered(ctx context.Context, arg SetAgentLastGrandfatheredParams) error {
	_, err := q.db.Exec(ctx, setAgentLastGrandfathered, arg.ImageDigest, arg.HostUid, arg.ID)
	return err
}

const setAgentMCPServers = `-- name: SetAgentMCPServers :exec
UPDATE agents
SET mcp_servers_jsonb = $1
WHERE id = $2
`

type SetAgentMCPServersParams struct {
	McpServersJsonb []byte
	ID              pgtype.UUID
}

func (q *Queries) SetAgentMCPServers(ctx context.Context, arg SetAgentMCPServersParams) error {
	_, err := q.db.Exec(ctx, setAgentMCPServers, arg.McpServersJsonb, arg.ID)
	return err
}

const setAgentRuntimeCaps = `-- name: SetAgentRuntimeCaps :exec
UPDATE agents
SET runtime_caps = $1
WHERE id = $2
`

type SetAgentRuntimeCapsParams struct {
	RuntimeCaps []byte
	ID          pgtype.UUID
}

func (q *Queries) SetAgentRuntimeCaps(ctx context.Context, arg SetAgentRuntimeCapsParams) error {
	_, err := q.db.Exec(ctx, setAgentRuntimeCaps, arg.RuntimeCaps, arg.ID)
	return err
}
