// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m8_audit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAgentAnchoredAudit = `-- name: InsertAgentAnchoredAudit :one

INSERT INTO chat_mutation_audit (
    chat_session_id, chat_message_id, agent_instance_id,
    verb, args_jsonb, outcome,
    reversibility_class, affected_resource_id, affected_resource_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, created_at
`

type InsertAgentAnchoredAuditParams struct {
	ChatSessionID        pgtype.UUID
	ChatMessageID        pgtype.UUID
	AgentInstanceID      pgtype.UUID
	Verb                 string
	ArgsJsonb            []byte
	Outcome              string
	ReversibilityClass   int16
	AffectedResourceID   *string
	AffectedResourceType *string
}

type InsertAgentAnchoredAuditRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M8 audit-row queries.
// Used by supervisor/internal/garrisonmutate (agent-anchored writes) +
// dashboard /activity surface (agent-anchored filter).
// Variant of InsertChatMutationAudit accepting agent_instance_id. One and
// only one of chat_session_id or agent_instance_id should be non-NULL for
// create_ticket rows (FR-005 — Go-side enforcement; DB CHECK would break
// M7-era Server Action rows that have both anchors NULL legitimately).
func (q *Queries) InsertAgentAnchoredAudit(ctx context.Context, arg InsertAgentAnchoredAuditParams) (InsertAgentAnchoredAuditRow, error) {
	row := q.db.QueryRow(ctx, insertAgentAnchoredAudit,
		arg.ChatSessionID,
		arg.ChatMessageID,
		arg.AgentInstanceID,
		arg.Verb,
		arg.ArgsJsonb,
		arg.Outcome,
		arg.ReversibilityClass,
		arg.AffectedResourceID,
		arg.AffectedResourceType,
	)
	var i InsertAgentAnchoredAuditRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditByAgentInstance = `-- name: ListAuditByAgentInstance :many
SELECT id, chat_session_id, chat_message_id, agent_instance_id,
       verb, args_jsonb, outcome, reversibility_class,
       affected_resource_id, affected_resource_type, retention_class,
       created_at
  FROM chat_mutation_audit
 WHERE agent_instance_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListAuditByAgentInstanceParams struct {
	AgentInstanceID pgtype.UUID
	LimitN          int32
}

type ListAuditByAgentInstanceRow struct {
	ID                   pgtype.UUID
	ChatSessionID        pgtype.UUID
	ChatMessageID        pgtype.UUID
	AgentInstanceID      pgtype.UUID
	Verb                 string
	ArgsJsonb            []byte
	Outcome              string
	ReversibilityClass   int16
	AffectedResourceID   *string
	AffectedResourceType *string
	RetentionClass       *string
	CreatedAt            pgtype.Timestamptz
}

// FR-502 read-side: filter audit rows by agent_instance_id. Used by the
// dashboard /activity?agent_instance_id=<uuid> surface.
func (q *Queries) ListAuditByAgentInstance(ctx context.Context, arg ListAuditByAgentInstanceParams) ([]ListAuditByAgentInstanceRow, error) {
	rows, err := q.db.Query(ctx, listAuditByAgentInstance, arg.AgentInstanceID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditByAgentInstanceRow
	for rows.Next() {
		var i ListAuditByAgentInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.ChatMessageID,
			&i.AgentInstanceID,
			&i.Verb,
			&i.ArgsJsonb,
			&i.Outcome,
			&i.ReversibilityClass,
			&i.AffectedResourceID,
			&i.AffectedResourceType,
			&i.RetentionClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAgentAuditAnchors = `-- name: ResolveAgentAuditAnchors :one
SELECT
    cma.id AS audit_id,
    cma.verb,
    cma.outcome,
    cma.created_at AS audit_created_at,
    ai.id AS agent_instance_id,
    ai.ticket_id,
    ai.role_slug,
    a.id AS agent_id
  FROM chat_mutation_audit cma
  JOIN agent_instances ai ON ai.id = cma.agent_instance_id
  LEFT JOIN agents a ON a.department_id = ai.department_id
                    AND a.role_slug = ai.role_slug
 WHERE cma.id = $1
`

type ResolveAgentAuditAnchorsRow struct {
	AuditID         pgtype.UUID
	Verb            string
	Outcome         string
	AuditCreatedAt  pgtype.Timestamptz
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	RoleSlug        string
	AgentID         pgtype.UUID
}

// SC-012 forensic reconstruction: given an agent-anchored audit row, return
// the originating ticket + agent role within one query.
func (q *Queries) ResolveAgentAuditAnchors(ctx context.Context, auditID pgtype.UUID) (ResolveAgentAuditAnchorsRow, error) {
	row := q.db.QueryRow(ctx, resolveAgentAuditAnchors, auditID)
	var i ResolveAgentAuditAnchorsRow
	err := row.Scan(
		&i.AuditID,
		&i.Verb,
		&i.Outcome,
		&i.AuditCreatedAt,
		&i.AgentInstanceID,
		&i.TicketID,
		&i.RoleSlug,
		&i.AgentID,
	)
	return i, err
}
