// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m8_mcp_servers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMcpServerByID = `-- name: GetMcpServerByID :one
SELECT id, customer_slug, name, transport, url, bearer_token_path,
       status, failure_reason, registered_by, registered_at,
       created_at, updated_at
  FROM mcp_servers
 WHERE id = $1
`

func (q *Queries) GetMcpServerByID(ctx context.Context, id pgtype.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMcpServerByID, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.CustomerSlug,
		&i.Name,
		&i.Transport,
		&i.Url,
		&i.BearerTokenPath,
		&i.Status,
		&i.FailureReason,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMcpServer = `-- name: InsertMcpServer :one

INSERT INTO mcp_servers (
    customer_slug, name, transport, url, bearer_token_path, registered_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, status
`

type InsertMcpServerParams struct {
	CustomerSlug    string
	Name            string
	Transport       string
	Url             *string
	BearerTokenPath *string
	RegisteredBy    pgtype.UUID
}

type InsertMcpServerRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Status    string
}

// M8 MCP-server registry queries.
// Used by:
//   - supervisor/internal/mcpserverwork/worker.go (read pending rows;
//     UPDATE status on completion).
//   - dashboard/lib/queries/mcpServers.ts (read-side via Drizzle; the
//     dashboard's Server Action writes via Drizzle directly per plan §13).
//   - supervisor/internal/garrisonmutate/register_mcp_server.go (the
//     Server-Action verb writes through Drizzle on the dashboard side,
//     but unit tests for the supervisor-side may use these queries).
//
// Server Action write path (M8 alpha calls this from the dashboard's
// mcpServer.ts via Drizzle directly; this query is for supervisor-side
// test fixtures + completeness). Row lands with status='pending'; the
// INSERT trigger emits the pg_notify; the worker picks it up.
func (q *Queries) InsertMcpServer(ctx context.Context, arg InsertMcpServerParams) (InsertMcpServerRow, error) {
	row := q.db.QueryRow(ctx, insertMcpServer,
		arg.CustomerSlug,
		arg.Name,
		arg.Transport,
		arg.Url,
		arg.BearerTokenPath,
		arg.RegisteredBy,
	)
	var i InsertMcpServerRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Status)
	return i, err
}

const listMcpServersByCustomer = `-- name: ListMcpServersByCustomer :many
SELECT id, customer_slug, name, transport, url, bearer_token_path,
       status, failure_reason, registered_by, registered_at,
       created_at, updated_at
  FROM mcp_servers
 WHERE customer_slug = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListMcpServersByCustomer(ctx context.Context, customerSlug string) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMcpServersByCustomer, customerSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.CustomerSlug,
			&i.Name,
			&i.Transport,
			&i.Url,
			&i.BearerTokenPath,
			&i.Status,
			&i.FailureReason,
			&i.RegisteredBy,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMcpServers = `-- name: ListPendingMcpServers :many
SELECT id, customer_slug, name, transport, url, bearer_token_path
  FROM mcp_servers
 WHERE status = 'pending'
 ORDER BY created_at ASC
`

type ListPendingMcpServersRow struct {
	ID              pgtype.UUID
	CustomerSlug    string
	Name            string
	Transport       string
	Url             *string
	BearerTokenPath *string
}

// Used by the supervisor's mcpserverwork worker at startup to recover any
// registration requests that landed while the worker was down. Idempotent
// — re-enqueues each pending row's MCPJungle API call.
func (q *Queries) ListPendingMcpServers(ctx context.Context) ([]ListPendingMcpServersRow, error) {
	rows, err := q.db.Query(ctx, listPendingMcpServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMcpServersRow
	for rows.Next() {
		var i ListPendingMcpServersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerSlug,
			&i.Name,
			&i.Transport,
			&i.Url,
			&i.BearerTokenPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMcpServerStatus = `-- name: UpdateMcpServerStatus :exec
UPDATE mcp_servers
   SET status = $1,
       failure_reason = $2,
       registered_at = CASE WHEN $1 = 'registered' THEN NOW() ELSE registered_at END,
       updated_at = NOW()
 WHERE id = $3
`

type UpdateMcpServerStatusParams struct {
	Status        string
	FailureReason *string
	ID            pgtype.UUID
}

// Worker write path. On MCPJungle API success: status='registered',
// registered_at=NOW(). On failure: status='failed' + failure_reason. The
// worker also writes one chat_mutation_audit row with verb=
// 'register_mcp_server' + outcome='success'|'failed' (FR-306).
func (q *Queries) UpdateMcpServerStatus(ctx context.Context, arg UpdateMcpServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateMcpServerStatus, arg.Status, arg.FailureReason, arg.ID)
	return err
}
