// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m8_tickets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentInstanceTicketID = `-- name: GetAgentInstanceTicketID :one
SELECT ticket_id
  FROM agent_instances
 WHERE id = $1
`

// Used by the create_ticket verb's auto-inherit path (FR-006): when an
// agent caller omits parent_ticket_id, fall back to the agent's current
// spawn's ticket_id.
func (q *Queries) GetAgentInstanceTicketID(ctx context.Context, agentInstanceID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceTicketID, agentInstanceID)
	var ticket_id pgtype.UUID
	err := row.Scan(&ticket_id)
	return ticket_id, err
}

const getTicketDependencyChain = `-- name: GetTicketDependencyChain :many
WITH RECURSIVE chain(chain_id, depth) AS (
    SELECT t.depends_on_ticket_id, 1
      FROM tickets t
     WHERE t.id = $1
       AND t.depends_on_ticket_id IS NOT NULL
    UNION ALL
    SELECT t.depends_on_ticket_id, c.depth + 1
      FROM tickets t
      JOIN chain c ON t.id = c.chain_id
     WHERE t.depends_on_ticket_id IS NOT NULL
       AND c.depth < $2::int
)
SELECT chain_id, depth FROM chain
`

type GetTicketDependencyChainParams struct {
	StartID  pgtype.UUID
	DepthCap int32
}

type GetTicketDependencyChainRow struct {
	ChainID pgtype.UUID
	Depth   int32
}

// O(N) walk for cycle detection. Caller iterates up to depth_cap (32 per
// FR-103); rejects on cycle (next_id == start_id) or exhaustion.
func (q *Queries) GetTicketDependencyChain(ctx context.Context, arg GetTicketDependencyChainParams) ([]GetTicketDependencyChainRow, error) {
	rows, err := q.db.Query(ctx, getTicketDependencyChain, arg.StartID, arg.DepthCap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketDependencyChainRow
	for rows.Next() {
		var i GetTicketDependencyChainRow
		if err := rows.Scan(&i.ChainID, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketSatisfactionState = `-- name: GetTicketSatisfactionState :one
SELECT t.column_slug,
       d.dependency_satisfaction_columns
  FROM tickets t
  JOIN departments d ON d.id = t.department_id
 WHERE t.id = $1
`

type GetTicketSatisfactionStateRow struct {
	ColumnSlug                    string
	DependencySatisfactionColumns []byte
}

// Read by spawn-prep (FR-102) to decide whether to spawn a dependent.
// Returns the predecessor's column_slug + the predecessor's dept's
// dependency_satisfaction_columns array. Caller compares.
func (q *Queries) GetTicketSatisfactionState(ctx context.Context, predecessorID pgtype.UUID) (GetTicketSatisfactionStateRow, error) {
	row := q.db.QueryRow(ctx, getTicketSatisfactionState, predecessorID)
	var i GetTicketSatisfactionStateRow
	err := row.Scan(&i.ColumnSlug, &i.DependencySatisfactionColumns)
	return i, err
}

const insertTicketM8 = `-- name: InsertTicketM8 :one

INSERT INTO tickets (
    department_id, objective, acceptance_criteria,
    column_slug, metadata, origin,
    created_via_chat_session_id, parent_ticket_id, depends_on_ticket_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, created_at
`

type InsertTicketM8Params struct {
	DepartmentID            pgtype.UUID
	Objective               string
	AcceptanceCriteria      *string
	ColumnSlug              string
	Metadata                []byte
	Origin                  string
	CreatedViaChatSessionID pgtype.UUID
	ParentTicketID          pgtype.UUID
	DependsOnTicketID       pgtype.UUID
}

type InsertTicketM8Row struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M8 ticket queries.
// Used by:
//   - supervisor/internal/garrisonmutate/verbs_tickets.go (create_ticket
//     agent-caller extension + cycle walker + parent auto-inherit).
//   - supervisor/internal/spawn/spawn.go (dependency-satisfaction check
//     at spawn-prep + transition-listener unblock).
//
// Variant of InsertChatTicket carrying both parent_ticket_id (M6) and
// depends_on_ticket_id (M8). Caller resolves auto-inherit + cycle check
// before invocation.
func (q *Queries) InsertTicketM8(ctx context.Context, arg InsertTicketM8Params) (InsertTicketM8Row, error) {
	row := q.db.QueryRow(ctx, insertTicketM8,
		arg.DepartmentID,
		arg.Objective,
		arg.AcceptanceCriteria,
		arg.ColumnSlug,
		arg.Metadata,
		arg.Origin,
		arg.CreatedViaChatSessionID,
		arg.ParentTicketID,
		arg.DependsOnTicketID,
	)
	var i InsertTicketM8Row
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listBlockedDependents = `-- name: ListBlockedDependents :many
SELECT id, department_id, column_slug
  FROM tickets
 WHERE depends_on_ticket_id = $1
   AND column_slug = 'todo'
`

type ListBlockedDependentsRow struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	ColumnSlug   string
}

// Read by the dispatcher's transition listener (FR-105). For every
// ticket transition, find tickets with depends_on_ticket_id pointing at
// the transitioning ticket that are still in column_slug='todo'.
func (q *Queries) ListBlockedDependents(ctx context.Context, predecessorID pgtype.UUID) ([]ListBlockedDependentsRow, error) {
	rows, err := q.db.Query(ctx, listBlockedDependents, predecessorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedDependentsRow
	for rows.Next() {
		var i ListBlockedDependentsRow
		if err := rows.Scan(&i.ID, &i.DepartmentID, &i.ColumnSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
