// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m8_throttle.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeptWeeklyState = `-- name: GetDeptWeeklyState :one

SELECT
    d.id AS department_id,
    d.slug AS department_slug,
    d.weekly_ticket_budget,
    (SELECT COUNT(*) FROM tickets
       WHERE department_id = d.id
         AND created_at > NOW() - INTERVAL '7 days')::bigint AS current_count
  FROM departments d
 WHERE d.id = $1
`

type GetDeptWeeklyStateRow struct {
	DepartmentID       pgtype.UUID
	DepartmentSlug     string
	WeeklyTicketBudget *int32
	CurrentCount       int64
}

// M8 runaway-control queries.
// Used by supervisor/internal/throttle/dept_weekly.go.
// Returns the rolling-7-day ticket-creation count for the department + the
// configured budget (NULL = unlimited; M8 alpha default). Caller decides
// whether count + 1 would exceed budget; on rejection writes a
// throttle_events row (M6's existing InsertThrottleEvent query, with
// kind='dept_weekly_ticket_budget_exceeded' added to the CHECK in M8).
func (q *Queries) GetDeptWeeklyState(ctx context.Context, departmentID pgtype.UUID) (GetDeptWeeklyStateRow, error) {
	row := q.db.QueryRow(ctx, getDeptWeeklyState, departmentID)
	var i GetDeptWeeklyStateRow
	err := row.Scan(
		&i.DepartmentID,
		&i.DepartmentSlug,
		&i.WeeklyTicketBudget,
		&i.CurrentCount,
	)
	return i, err
}

const listDeptWeeklyStateAll = `-- name: ListDeptWeeklyStateAll :many
SELECT
    d.id AS department_id,
    d.slug AS department_slug,
    d.weekly_ticket_budget,
    (SELECT COUNT(*) FROM tickets
       WHERE department_id = d.id
         AND created_at > NOW() - INTERVAL '7 days')::bigint AS current_count,
    (SELECT MAX(fired_at) FROM throttle_events
       WHERE kind = 'dept_weekly_ticket_budget_exceeded'
         AND (payload->>'department_id')::uuid = d.id) AS last_fired_at
  FROM departments d
 ORDER BY d.slug ASC
`

type ListDeptWeeklyStateAllRow struct {
	DepartmentID       pgtype.UUID
	DepartmentSlug     string
	WeeklyTicketBudget *int32
	CurrentCount       int64
	LastFiredAt        interface{}
}

// Used by the dashboard /hygiene runaway-control surface (FR-501).
// Returns one row per department with the rolling-window count + budget +
// the most recent throttle_events.fired_at for kind='dept_weekly_ticket_budget_exceeded'
// (NULL if never fired). Single query so the dashboard render is one DB
// round-trip.
func (q *Queries) ListDeptWeeklyStateAll(ctx context.Context) ([]ListDeptWeeklyStateAllRow, error) {
	rows, err := q.db.Query(ctx, listDeptWeeklyStateAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeptWeeklyStateAllRow
	for rows.Next() {
		var i ListDeptWeeklyStateAllRow
		if err := rows.Scan(
			&i.DepartmentID,
			&i.DepartmentSlug,
			&i.WeeklyTicketBudget,
			&i.CurrentCount,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
