// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m8_vault.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAgentScopedSecret = `-- name: InsertAgentScopedSecret :exec
INSERT INTO agent_role_secrets (
    role_slug, agent_id, secret_path, env_var_name, customer_id, granted_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertAgentScopedSecretParams struct {
	RoleSlug   string
	AgentID    pgtype.UUID
	SecretPath string
	EnvVarName string
	CustomerID pgtype.UUID
	GrantedBy  string
}

// Used by the supervisor's mcpjungle reconciler at agent activation:
// after creating the McpClient + writing the bearer token to Infisical
// at mcpjungle/agents/<agent-id>, insert this grant so the spawn-time
// vault fetcher will resolve the path for that specific agent.
// role_slug carries the agent's role (for forensics + the trigger's
// secret_metadata.allowed_role_slugs aggregation); agent_id is the
// discriminator that makes the grant agent-scoped.
func (q *Queries) InsertAgentScopedSecret(ctx context.Context, arg InsertAgentScopedSecretParams) error {
	_, err := q.db.Exec(ctx, insertAgentScopedSecret,
		arg.RoleSlug,
		arg.AgentID,
		arg.SecretPath,
		arg.EnvVarName,
		arg.CustomerID,
		arg.GrantedBy,
	)
	return err
}

const listGrantsForRoleAndAgent = `-- name: ListGrantsForRoleAndAgent :many

SELECT id, role_slug, agent_id, secret_path, env_var_name, customer_id, granted_at
  FROM agent_role_secrets
 WHERE customer_id = $1
   AND (
     (role_slug = $2 AND agent_id IS NULL)
     OR
     (agent_id = $3)
   )
 ORDER BY env_var_name
`

type ListGrantsForRoleAndAgentParams struct {
	CustomerID pgtype.UUID
	RoleSlug   string
	AgentID    pgtype.UUID
}

type ListGrantsForRoleAndAgentRow struct {
	ID         pgtype.UUID
	RoleSlug   string
	AgentID    pgtype.UUID
	SecretPath string
	EnvVarName string
	CustomerID pgtype.UUID
	GrantedAt  pgtype.Timestamptz
}

// M8 vault-grant queries.
// Used by supervisor/internal/vault/grants.go.
//
// The M2.3 agent_role_secrets table is extended in M8 with:
//   - id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()
//   - agent_id UUID NULL REFERENCES agents(id) ON DELETE CASCADE
//
// Existing role-scoped grants have agent_id IS NULL. M8 agent-scoped
// grants (MCPJungle bearer tokens) have agent_id non-NULL. Partial
// unique indexes enforce per-anchor uniqueness.
// Returns both role-scoped grants (role_slug=<role> AND agent_id IS NULL)
// and agent-scoped grants (agent_id=<agent>). Used at spawn time to fetch
// every vault path the agent is authorised to read.
func (q *Queries) ListGrantsForRoleAndAgent(ctx context.Context, arg ListGrantsForRoleAndAgentParams) ([]ListGrantsForRoleAndAgentRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForRoleAndAgent, arg.CustomerID, arg.RoleSlug, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForRoleAndAgentRow
	for rows.Next() {
		var i ListGrantsForRoleAndAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleSlug,
			&i.AgentID,
			&i.SecretPath,
			&i.EnvVarName,
			&i.CustomerID,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
