// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: m9_schedule.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceScheduledTask = `-- name: AdvanceScheduledTask :exec
UPDATE scheduled_tasks
   SET next_fire_at  = $1,
       last_fired_at = CASE WHEN $2::bool
                            THEN $3::timestamptz
                            ELSE last_fired_at END,
       updated_at    = now()
 WHERE id = $4
`

type AdvanceScheduledTaskParams struct {
	NextFireAt pgtype.Timestamptz
	Fired      bool
	FiredAt    pgtype.Timestamptz
	ID         pgtype.UUID
}

// Always advances exactly one future slot regardless of outcome
// (collapse + skip + defer all consume the slot; FR-104). fired is
// "this slot actually fired": last_fired_at updates ONLY then (FR-107:
// {{last_fired_at}} means the previous *firing*, not the previous
// claim).
func (q *Queries) AdvanceScheduledTask(ctx context.Context, arg AdvanceScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, advanceScheduledTask,
		arg.NextFireAt,
		arg.Fired,
		arg.FiredAt,
		arg.ID,
	)
	return err
}

const claimDueScheduledTasks = `-- name: ClaimDueScheduledTasks :many

SELECT id, name, department_id, role_slug, mode, schedule_expr,
       next_fire_at, objective_template, acceptance_criteria_template,
       paused, deleted_at, last_fired_at, created_at, updated_at
  FROM scheduled_tasks
 WHERE NOT paused
   AND deleted_at IS NULL
   AND next_fire_at <= now()
 ORDER BY next_fire_at
   FOR UPDATE SKIP LOCKED
 LIMIT $1::int
`

// M9 scheduled wake-up queries (plan §sqlc).
// Used by:
//   - supervisor/internal/schedule/ (tick loop, firing transaction,
//     validation).
//   - supervisor/internal/spawn/oneshot.go (SpawnOneshot +
//     WriteFinalizeOneshot).
//   - supervisor/internal/finalize/ (oneshot double-commit guard).
//   - supervisor/internal/garrisonmutate/verbs_scheduled.go
//     (create_scheduled_task chat verb).
//   - supervisor/internal/dashboardapi/ (POST /schedule/validate).
//
// All parameters use sqlc.arg(name) exclusively (M7 retro gotcha).
// Tick-loop claim (FR-101). FOR UPDATE SKIP LOCKED gives each due slot
// at most one firing regardless of concurrent claim attempts. Paused
// and soft-deleted tasks are never claimed; the partial index
// idx_scheduled_tasks_due serves exactly this predicate. Claim limit
// (Deps.ClaimLimit, default 20) bounds tx size — remaining due tasks
// claim on the next tick.
func (q *Queries) ClaimDueScheduledTasks(ctx context.Context, claimLimit int32) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, claimDueScheduledTasks, claimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DepartmentID,
			&i.RoleSlug,
			&i.Mode,
			&i.ScheduleExpr,
			&i.NextFireAt,
			&i.ObjectiveTemplate,
			&i.AcceptanceCriteriaTemplate,
			&i.Paused,
			&i.DeletedAt,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasOpenTicketForTask = `-- name: HasOpenTicketForTask :one
SELECT EXISTS (
    SELECT 1
      FROM scheduled_task_runs r
      JOIN tickets t ON t.id = r.ticket_id
     WHERE r.scheduled_task_id = $1
       AND t.column_slug <> 'done'
) AS has_open_ticket
`

// Overlap predicate, ticket mode (FR-202): a slot arriving while a
// previously fired ticket is still open (not yet 'done', per spec
// US1-AS4) skips-and-advances. Any run of this task whose ticket has
// not reached 'done' counts — the overlap discipline itself guarantees
// at most one such ticket exists, so "any open" and "latest run's
// ticket open" coincide.
func (q *Queries) HasOpenTicketForTask(ctx context.Context, scheduledTaskID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenTicketForTask, scheduledTaskID)
	var has_open_ticket bool
	err := row.Scan(&has_open_ticket)
	return has_open_ticket, err
}

const hasRunningOneshotForTask = `-- name: HasRunningOneshotForTask :one
SELECT EXISTS (
    SELECT 1
      FROM scheduled_task_runs r
      LEFT JOIN agent_instances ai ON ai.id = r.agent_instance_id
     WHERE r.scheduled_task_id = $1
       AND r.outcome IN ('fired', 'gate_deferred')
       AND (r.agent_instance_id IS NULL OR ai.status = 'running')
) AS has_running_oneshot
`

// Overlap predicate, oneshot mode (FR-303): ANY run of the task counts
// as in-flight when its outcome is 'fired' or 'gate_deferred' AND
// either no instance has been backfilled yet (fired-but-not-yet-
// dispatched — closes the tick→dispatch window) or the joined instance
// is still running. gate_deferred is awaiting-poll-retry, hence
// in-flight. EXISTS over all runs (the HasOpenTicketForTask shape) —
// NOT latest-run-only: a skipped_overlap row becomes the latest run
// and would blind a latest-only predicate, double-firing the 2nd
// consecutive overlapping slot. Terminal runs stop counting via their
// own state: failed runs flip outcome to 'failed' (decision 5 failure
// paths), completed runs hold a non-running joined instance.
func (q *Queries) HasRunningOneshotForTask(ctx context.Context, scheduledTaskID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunningOneshotForTask, scheduledTaskID)
	var has_running_oneshot bool
	err := row.Scan(&has_running_oneshot)
	return has_running_oneshot, err
}

const insertScheduledTask = `-- name: InsertScheduledTask :one
INSERT INTO scheduled_tasks (
    name, department_id, role_slug, mode, schedule_expr,
    next_fire_at, objective_template, acceptance_criteria_template
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, name, department_id, role_slug, mode, schedule_expr,
          next_fire_at, objective_template, acceptance_criteria_template,
          paused, deleted_at, last_fired_at, created_at, updated_at
`

type InsertScheduledTaskParams struct {
	Name                       string
	DepartmentID               pgtype.UUID
	RoleSlug                   string
	Mode                       string
	ScheduleExpr               string
	NextFireAt                 pgtype.Timestamptz
	ObjectiveTemplate          string
	AcceptanceCriteriaTemplate string
}

// Verb + dashboard support. Caller (schedule.ValidateTask consumers)
// has already validated grammar, min-interval, future first slot,
// name uniqueness, department + role existence, non-empty templates,
// and mode before this INSERT; next_fire_at arrives precomputed.
func (q *Queries) InsertScheduledTask(ctx context.Context, arg InsertScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, insertScheduledTask,
		arg.Name,
		arg.DepartmentID,
		arg.RoleSlug,
		arg.Mode,
		arg.ScheduleExpr,
		arg.NextFireAt,
		arg.ObjectiveTemplate,
		arg.AcceptanceCriteriaTemplate,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.Mode,
		&i.ScheduleExpr,
		&i.NextFireAt,
		&i.ObjectiveTemplate,
		&i.AcceptanceCriteriaTemplate,
		&i.Paused,
		&i.DeletedAt,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduledTaskRun = `-- name: InsertScheduledTaskRun :one
INSERT INTO scheduled_task_runs (scheduled_task_id, slot_at, outcome, detail, ticket_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, fired_at
`

type InsertScheduledTaskRunParams struct {
	ScheduledTaskID pgtype.UUID
	SlotAt          pgtype.Timestamptz
	Outcome         string
	Detail          *string
	TicketID        pgtype.UUID
}

type InsertScheduledTaskRunRow struct {
	ID      pgtype.UUID
	FiredAt pgtype.Timestamptz
}

// One row per firing attempt (FR-108). detail carries the
// human-readable reason for non-fired outcomes; ticket_id is set for
// ticket-mode 'fired' rows only (oneshot anchors arrive later via
// SetRunAgentInstance).
func (q *Queries) InsertScheduledTaskRun(ctx context.Context, arg InsertScheduledTaskRunParams) (InsertScheduledTaskRunRow, error) {
	row := q.db.QueryRow(ctx, insertScheduledTaskRun,
		arg.ScheduledTaskID,
		arg.SlotAt,
		arg.Outcome,
		arg.Detail,
		arg.TicketID,
	)
	var i InsertScheduledTaskRunRow
	err := row.Scan(&i.ID, &i.FiredAt)
	return i, err
}

const insertScheduledTicket = `-- name: InsertScheduledTicket :one
INSERT INTO tickets (
    department_id, objective, acceptance_criteria, column_slug,
    metadata, origin
) VALUES (
    $1,
    $2,
    $3,
    'todo',
    jsonb_build_object('role_slug', $4::text),
    'scheduled'
)
RETURNING id, created_at
`

type InsertScheduledTicketParams struct {
	DepartmentID       pgtype.UUID
	Objective          string
	AcceptanceCriteria *string
	RoleSlug           string
}

type InsertScheduledTicketRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// M5.3 InsertChatTicket mirror for ticket-mode firings: dept, role,
// rendered objective + acceptance criteria, column_slug='todo'. The
// task's role_slug rides metadata (tickets carry no role column; the
// dispatcher routes by the dept/column channel as for any ticket).
// The tickets INSERT trigger emits the outbox row + the existing
// work.ticket.created.<dept>.todo notify in this same tx.
func (q *Queries) InsertScheduledTicket(ctx context.Context, arg InsertScheduledTicketParams) (InsertScheduledTicketRow, error) {
	row := q.db.QueryRow(ctx, insertScheduledTicket,
		arg.DepartmentID,
		arg.Objective,
		arg.AcceptanceCriteria,
		arg.RoleSlug,
	)
	var i InsertScheduledTicketRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listScheduledTasks = `-- name: ListScheduledTasks :many
SELECT id, name, department_id, role_slug, mode, schedule_expr,
       next_fire_at, objective_template, acceptance_criteria_template,
       paused, deleted_at, last_fired_at, created_at, updated_at
  FROM scheduled_tasks
 WHERE deleted_at IS NULL
 ORDER BY name
`

// Live tasks only; soft-deleted rows are history, not listings.
func (q *Queries) ListScheduledTasks(ctx context.Context) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DepartmentID,
			&i.RoleSlug,
			&i.Mode,
			&i.ScheduleExpr,
			&i.NextFireAt,
			&i.ObjectiveTemplate,
			&i.AcceptanceCriteriaTemplate,
			&i.Paused,
			&i.DeletedAt,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyOneshotDue = `-- name: NotifyOneshotDue :exec
SELECT pg_notify('work.scheduled.oneshot_due', $1::text)
`

// In-tx notify for oneshot firings. The channel literal is baked into
// the query (M6 retro gotcha 3: 'work.scheduled.oneshot_due' contains
// dots, so call sites must never assemble it — and every LISTEN
// statement must double-quote it). Composes with the outbox row on the
// tick tx so the dispatcher sees the notify only if the row committed.
func (q *Queries) NotifyOneshotDue(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, notifyOneshotDue, payload)
	return err
}

const selectScheduledTaskByName = `-- name: SelectScheduledTaskByName :one
SELECT id, name, department_id, role_slug, mode, schedule_expr,
       next_fire_at, objective_template, acceptance_criteria_template,
       paused, deleted_at, last_fired_at, created_at, updated_at
  FROM scheduled_tasks
 WHERE name = $1
   AND deleted_at IS NULL
`

// Name-uniqueness probe for validation (live rows only — a deleted
// task's name is reusable, matching idx_scheduled_tasks_name_live).
func (q *Queries) SelectScheduledTaskByName(ctx context.Context, name string) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, selectScheduledTaskByName, name)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.Mode,
		&i.ScheduleExpr,
		&i.NextFireAt,
		&i.ObjectiveTemplate,
		&i.AcceptanceCriteriaTemplate,
		&i.Paused,
		&i.DeletedAt,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectScheduledTaskByRunID = `-- name: SelectScheduledTaskByRunID :one
SELECT r.id AS run_id,
       r.slot_at,
       r.outcome,
       r.detail,
       r.agent_instance_id,
       st.id AS scheduled_task_id,
       st.name,
       st.department_id,
       st.role_slug,
       st.mode,
       st.schedule_expr,
       st.next_fire_at,
       st.objective_template,
       st.acceptance_criteria_template,
       st.paused,
       st.deleted_at,
       st.last_fired_at
  FROM scheduled_task_runs r
  JOIN scheduled_tasks st ON st.id = r.scheduled_task_id
 WHERE r.id = $1
`

type SelectScheduledTaskByRunIDRow struct {
	RunID                      pgtype.UUID
	SlotAt                     pgtype.Timestamptz
	Outcome                    string
	Detail                     *string
	AgentInstanceID            pgtype.UUID
	ScheduledTaskID            pgtype.UUID
	Name                       string
	DepartmentID               pgtype.UUID
	RoleSlug                   string
	Mode                       string
	ScheduleExpr               string
	NextFireAt                 pgtype.Timestamptz
	ObjectiveTemplate          string
	AcceptanceCriteriaTemplate string
	Paused                     bool
	DeletedAt                  pgtype.Timestamptz
	LastFiredAt                pgtype.Timestamptz
}

// Run → task join for SpawnOneshot prep (plan §2 step 1): the
// dispatcher hands over a scheduled_task_run_id; this resolves the
// task identity, templates, and last-fired state in one read.
func (q *Queries) SelectScheduledTaskByRunID(ctx context.Context, runID pgtype.UUID) (SelectScheduledTaskByRunIDRow, error) {
	row := q.db.QueryRow(ctx, selectScheduledTaskByRunID, runID)
	var i SelectScheduledTaskByRunIDRow
	err := row.Scan(
		&i.RunID,
		&i.SlotAt,
		&i.Outcome,
		&i.Detail,
		&i.AgentInstanceID,
		&i.ScheduledTaskID,
		&i.Name,
		&i.DepartmentID,
		&i.RoleSlug,
		&i.Mode,
		&i.ScheduleExpr,
		&i.NextFireAt,
		&i.ObjectiveTemplate,
		&i.AcceptanceCriteriaTemplate,
		&i.Paused,
		&i.DeletedAt,
		&i.LastFiredAt,
	)
	return i, err
}

const selectScheduledTaskRunFinalizedState = `-- name: SelectScheduledTaskRunFinalizedState :one
SELECT (r.structured_outcome IS NOT NULL) AS finalized,
       r.outcome,
       r.agent_instance_id
  FROM scheduled_task_runs r
 WHERE r.id = $1
`

type SelectScheduledTaskRunFinalizedStateRow struct {
	Finalized       interface{}
	Outcome         string
	AgentInstanceID pgtype.UUID
}

// Oneshot double-commit guard (FR-260 analog, keyed by run id): the
// finalize MCP server and WriteFinalizeOneshot both consult this
// before committing. A non-NULL structured_outcome means the payload
// already landed.
func (q *Queries) SelectScheduledTaskRunFinalizedState(ctx context.Context, runID pgtype.UUID) (SelectScheduledTaskRunFinalizedStateRow, error) {
	row := q.db.QueryRow(ctx, selectScheduledTaskRunFinalizedState, runID)
	var i SelectScheduledTaskRunFinalizedStateRow
	err := row.Scan(&i.Finalized, &i.Outcome, &i.AgentInstanceID)
	return i, err
}

const setRunAgentInstance = `-- name: SetRunAgentInstance :exec
UPDATE scheduled_task_runs
   SET agent_instance_id = $1
 WHERE id = $2
`

type SetRunAgentInstanceParams struct {
	AgentInstanceID pgtype.UUID
	ID              pgtype.UUID
}

// Backfills the oneshot anchor at spawn (SpawnOneshot step 3): run row
// gains the agent_instances FK so completion state reads through the
// joined instance status (plan decision 5).
func (q *Queries) SetRunAgentInstance(ctx context.Context, arg SetRunAgentInstanceParams) error {
	_, err := q.db.Exec(ctx, setRunAgentInstance, arg.AgentInstanceID, arg.ID)
	return err
}

const updateRunOutcome = `-- name: UpdateRunOutcome :exec
UPDATE scheduled_task_runs
   SET outcome = $1,
       detail  = $2
 WHERE id = $3
`

type UpdateRunOutcomeParams struct {
	Outcome string
	Detail  *string
	ID      pgtype.UUID
}

// Oneshot gate-defer / pre-pipeline spawn failure. gate_deferred is
// NON-terminal for oneshot runs: a successful poll re-dispatch clears
// the run back to 'fired' via this same query before the instance
// insert (FR-401).
func (q *Queries) UpdateRunOutcome(ctx context.Context, arg UpdateRunOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateRunOutcome, arg.Outcome, arg.Detail, arg.ID)
	return err
}

const updateRunStructuredOutcome = `-- name: UpdateRunStructuredOutcome :exec
UPDATE scheduled_task_runs
   SET structured_outcome = $1
 WHERE id = $2
`

type UpdateRunStructuredOutcomeParams struct {
	StructuredOutcome []byte
	ID                pgtype.UUID
}

// WriteFinalizeOneshot commit: full finalize payload + the
// verification sub-object, in the same tx as the palace writes and the
// terminal agent_instances row.
func (q *Queries) UpdateRunStructuredOutcome(ctx context.Context, arg UpdateRunStructuredOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateRunStructuredOutcome, arg.StructuredOutcome, arg.ID)
	return err
}
