// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	RoleSlug     string
	AgentMd      string
	Model        string
	Skills       []byte
	McpTools     []byte
	ListensFor   []byte
	PalaceWing   *string
	Status       string
	CreatedAt    pgtype.Timestamptz
}

type AgentInstance struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	TicketID     pgtype.UUID
	Pid          *int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Status       string
	ExitReason   *string
	TotalCostUsd pgtype.Numeric
	WakeUpStatus *string
	RoleSlug     string
}

type Company struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Department struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	ConcurrencyCap int32
	CreatedAt      pgtype.Timestamptz
	CompanyID      pgtype.UUID
	WorkspacePath  *string
	Workflow       []byte
}

type EventOutbox struct {
	ID          pgtype.UUID
	Channel     string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type Ticket struct {
	ID                 pgtype.UUID
	DepartmentID       pgtype.UUID
	Objective          string
	CreatedAt          pgtype.Timestamptz
	ColumnSlug         string
	AcceptanceCriteria *string
	Metadata           []byte
	Origin             string
}

type TicketTransition struct {
	ID                         pgtype.UUID
	TicketID                   pgtype.UUID
	FromColumn                 *string
	ToColumn                   string
	TriggeredByAgentInstanceID pgtype.UUID
	TriggeredByUser            bool
	At                         pgtype.Timestamptz
	HygieneStatus              *string
}
