// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                  pgtype.UUID
	DepartmentID        pgtype.UUID
	RoleSlug            string
	AgentMd             string
	Model               string
	Skills              []byte
	McpTools            []byte
	ListensFor          []byte
	PalaceWing          *string
	Status              string
	CreatedAt           pgtype.Timestamptz
	McpConfig           []byte
	UpdatedAt           pgtype.Timestamptz
	ImageDigest         *string
	RuntimeCaps         []byte
	EgressGrantJsonb    []byte
	McpServersJsonb     []byte
	LastGrandfatheredAt pgtype.Timestamptz
	HostUid             *int32
}

type AgentContainerEvent struct {
	ID              pgtype.UUID
	AgentID         pgtype.UUID
	Kind            string
	ImageDigest     *string
	StartedAt       pgtype.Timestamptz
	StoppedAt       pgtype.Timestamptz
	StopReason      *string
	CgroupCapsJsonb []byte
	RetentionClass  *string
	CreatedAt       pgtype.Timestamptz
}

type AgentInstallJournal struct {
	ID           pgtype.UUID
	ProposalID   pgtype.UUID
	Step         string
	Outcome      string
	ErrorKind    *string
	PayloadJsonb []byte
	CreatedAt    pgtype.Timestamptz
}

type AgentInstance struct {
	ID                 pgtype.UUID
	DepartmentID       pgtype.UUID
	TicketID           pgtype.UUID
	Pid                *int32
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	Status             string
	ExitReason         *string
	TotalCostUsd       pgtype.Numeric
	WakeUpStatus       *string
	RoleSlug           string
	ImageDigest        string
	PreambleHash       string
	ClaudeMdHash       *string
	OriginatingAuditID pgtype.UUID
	ScheduledTaskRunID pgtype.UUID
}

type AgentRoleSecret struct {
	RoleSlug   string
	SecretPath string
	EnvVarName string
	CustomerID pgtype.UUID
	GrantedAt  pgtype.Timestamptz
	GrantedBy  string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         pgtype.UUID
	AgentID    pgtype.UUID
}

type ChatMessage struct {
	ID               pgtype.UUID
	SessionID        pgtype.UUID
	TurnIndex        int32
	Role             string
	Status           string
	Content          *string
	TokensInput      *int32
	TokensOutput     *int32
	CostUsd          pgtype.Numeric
	ErrorKind        *string
	RawEventEnvelope []byte
	CreatedAt        pgtype.Timestamptz
	TerminatedAt     pgtype.Timestamptz
}

type ChatMutationAudit struct {
	ID                   pgtype.UUID
	ChatSessionID        pgtype.UUID
	ChatMessageID        pgtype.UUID
	Verb                 string
	ArgsJsonb            []byte
	Outcome              string
	ReversibilityClass   int16
	AffectedResourceID   *string
	AffectedResourceType *string
	CreatedAt            pgtype.Timestamptz
	RetentionClass       *string
	AgentInstanceID      pgtype.UUID
}

type ChatSession struct {
	ID                 pgtype.UUID
	StartedByUserID    pgtype.UUID
	StartedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	Status             string
	TotalCostUsd       pgtype.Numeric
	ClaudeSessionLabel *string
	IsArchived         bool
}

type Company struct {
	ID             pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	DailyBudgetUsd pgtype.Numeric
	PauseUntil     pgtype.Timestamptz
	CustomerSlug   string
}

type Department struct {
	ID                            pgtype.UUID
	Slug                          string
	Name                          string
	ConcurrencyCap                int32
	CreatedAt                     pgtype.Timestamptz
	CompanyID                     pgtype.UUID
	WorkspacePath                 *string
	Workflow                      []byte
	DependencySatisfactionColumns []byte
	WeeklyTicketBudget            *int32
}

type EventOutbox struct {
	ID          pgtype.UUID
	Channel     string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type HiringProposal struct {
	ID                      pgtype.UUID
	RoleTitle               string
	DepartmentSlug          string
	JustificationMd         string
	SkillsSummaryMd         *string
	ProposedVia             string
	ProposedByChatSessionID pgtype.UUID
	Status                  string
	CreatedAt               pgtype.Timestamptz
	TargetAgentID           pgtype.UUID
	ProposalType            string
	SkillDiffJsonb          []byte
	ProposalSnapshotJsonb   []byte
	SkillDigestAtPropose    *string
	ApprovedAt              pgtype.Timestamptz
	ApprovedBy              pgtype.UUID
	RejectedAt              pgtype.Timestamptz
	RejectedReason          *string
}

type IngressDelivery struct {
	ID                 pgtype.UUID
	ConnectorID        string
	ExternalDeliveryID string
	TicketID           pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type McpServer struct {
	ID              pgtype.UUID
	CustomerSlug    string
	Name            string
	Transport       string
	Url             *string
	BearerTokenPath *string
	Status          string
	FailureReason   *string
	RegisteredBy    pgtype.UUID
	RegisteredAt    pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PendingAction struct {
	ID              pgtype.UUID
	ActionType      string
	Target          []byte
	RenderedPayload string
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	Tier            string
	TierReason      string
	Status          string
	ApprovedBy      *string
	DispatchedAt    pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type PendingActionOutcome struct {
	ID                pgtype.UUID
	PendingActionID   pgtype.UUID
	AgentInstanceID   pgtype.UUID
	Outcome           string
	Detail            *string
	StructuredOutcome []byte
	CreatedAt         pgtype.Timestamptz
}

type ScheduledTask struct {
	ID                         pgtype.UUID
	Name                       string
	DepartmentID               pgtype.UUID
	RoleSlug                   string
	Mode                       string
	ScheduleExpr               string
	NextFireAt                 pgtype.Timestamptz
	ObjectiveTemplate          string
	AcceptanceCriteriaTemplate string
	Paused                     bool
	DeletedAt                  pgtype.Timestamptz
	LastFiredAt                pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type ScheduledTaskRun struct {
	ID                pgtype.UUID
	ScheduledTaskID   pgtype.UUID
	SlotAt            pgtype.Timestamptz
	FiredAt           pgtype.Timestamptz
	Outcome           string
	Detail            *string
	TicketID          pgtype.UUID
	AgentInstanceID   pgtype.UUID
	StructuredOutcome []byte
}

type SecretMetadatum struct {
	SecretPath       string
	CustomerID       pgtype.UUID
	Provenance       string
	RotationCadence  pgtype.Interval
	LastRotatedAt    pgtype.Timestamptz
	LastAccessedAt   pgtype.Timestamptz
	AllowedRoleSlugs []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RotationProvider string
}

type ThrottleEvent struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Kind      string
	FiredAt   pgtype.Timestamptz
	Payload   []byte
}

type Ticket struct {
	ID                      pgtype.UUID
	DepartmentID            pgtype.UUID
	Objective               string
	CreatedAt               pgtype.Timestamptz
	ColumnSlug              string
	AcceptanceCriteria      *string
	Metadata                []byte
	Origin                  string
	CreatedViaChatSessionID pgtype.UUID
	ParentTicketID          pgtype.UUID
	DependsOnTicketID       pgtype.UUID
}

type TicketTransition struct {
	ID                             pgtype.UUID
	TicketID                       pgtype.UUID
	FromColumn                     *string
	ToColumn                       string
	TriggeredByAgentInstanceID     pgtype.UUID
	TriggeredByUser                bool
	At                             pgtype.Timestamptz
	HygieneStatus                  *string
	SuspectedSecretPatternCategory *string
}

type VaultAccessLog struct {
	ID              pgtype.UUID
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	SecretPath      string
	CustomerID      pgtype.UUID
	Outcome         string
	Timestamp       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
}
