// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	RoleSlug     string
	AgentMd      string
	Model        string
	Skills       []byte
	McpTools     []byte
	ListensFor   []byte
	PalaceWing   *string
	Status       string
	CreatedAt    pgtype.Timestamptz
	McpConfig    []byte
	UpdatedAt    pgtype.Timestamptz
}

type AgentInstance struct {
	ID           pgtype.UUID
	DepartmentID pgtype.UUID
	TicketID     pgtype.UUID
	Pid          *int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Status       string
	ExitReason   *string
	TotalCostUsd pgtype.Numeric
	WakeUpStatus *string
	RoleSlug     string
}

type AgentRoleSecret struct {
	RoleSlug   string
	SecretPath string
	EnvVarName string
	CustomerID pgtype.UUID
	GrantedAt  pgtype.Timestamptz
	GrantedBy  string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ChatMessage struct {
	ID               pgtype.UUID
	SessionID        pgtype.UUID
	TurnIndex        int32
	Role             string
	Status           string
	Content          *string
	TokensInput      *int32
	TokensOutput     *int32
	CostUsd          pgtype.Numeric
	ErrorKind        *string
	RawEventEnvelope []byte
	CreatedAt        pgtype.Timestamptz
	TerminatedAt     pgtype.Timestamptz
}

type ChatMutationAudit struct {
	ID                   pgtype.UUID
	ChatSessionID        pgtype.UUID
	ChatMessageID        pgtype.UUID
	Verb                 string
	ArgsJsonb            []byte
	Outcome              string
	ReversibilityClass   int16
	AffectedResourceID   *string
	AffectedResourceType *string
	CreatedAt            pgtype.Timestamptz
}

type ChatSession struct {
	ID                 pgtype.UUID
	StartedByUserID    pgtype.UUID
	StartedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	Status             string
	TotalCostUsd       pgtype.Numeric
	ClaudeSessionLabel *string
	IsArchived         bool
}

type Company struct {
	ID             pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	DailyBudgetUsd pgtype.Numeric
	PauseUntil     pgtype.Timestamptz
}

type Department struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	ConcurrencyCap int32
	CreatedAt      pgtype.Timestamptz
	CompanyID      pgtype.UUID
	WorkspacePath  *string
	Workflow       []byte
}

type EventOutbox struct {
	ID          pgtype.UUID
	Channel     string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type HiringProposal struct {
	ID                      pgtype.UUID
	RoleTitle               string
	DepartmentSlug          string
	JustificationMd         string
	SkillsSummaryMd         *string
	ProposedVia             string
	ProposedByChatSessionID pgtype.UUID
	Status                  string
	CreatedAt               pgtype.Timestamptz
}

type SecretMetadatum struct {
	SecretPath       string
	CustomerID       pgtype.UUID
	Provenance       string
	RotationCadence  pgtype.Interval
	LastRotatedAt    pgtype.Timestamptz
	LastAccessedAt   pgtype.Timestamptz
	AllowedRoleSlugs []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RotationProvider string
}

type ThrottleEvent struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Kind      string
	FiredAt   pgtype.Timestamptz
	Payload   []byte
}

type Ticket struct {
	ID                      pgtype.UUID
	DepartmentID            pgtype.UUID
	Objective               string
	CreatedAt               pgtype.Timestamptz
	ColumnSlug              string
	AcceptanceCriteria      *string
	Metadata                []byte
	Origin                  string
	CreatedViaChatSessionID pgtype.UUID
	ParentTicketID          pgtype.UUID
}

type TicketTransition struct {
	ID                             pgtype.UUID
	TicketID                       pgtype.UUID
	FromColumn                     *string
	ToColumn                       string
	TriggeredByAgentInstanceID     pgtype.UUID
	TriggeredByUser                bool
	At                             pgtype.Timestamptz
	HygieneStatus                  *string
	SuspectedSecretPatternCategory *string
}

type VaultAccessLog struct {
	ID              pgtype.UUID
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	SecretPath      string
	CustomerID      pgtype.UUID
	Outcome         string
	Timestamp       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
}
