// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secret_metadata.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStaleSecrets = `-- name: ListStaleSecrets :many
SELECT secret_path, customer_id, provenance, rotation_cadence,
       last_rotated_at, last_accessed_at, allowed_role_slugs
  FROM secret_metadata
 WHERE last_rotated_at IS NOT NULL
   AND rotation_cadence <> 'never'
   AND (now() - last_rotated_at) > rotation_cadence
`

type ListStaleSecretsRow struct {
	SecretPath       string
	CustomerID       pgtype.UUID
	Provenance       string
	RotationCadence  pgtype.Interval
	LastRotatedAt    pgtype.Timestamptz
	LastAccessedAt   pgtype.Timestamptz
	AllowedRoleSlugs []string
}

// Exists for M3 dashboard's "stale secrets" view. M2.3 does not call this.
func (q *Queries) ListStaleSecrets(ctx context.Context) ([]ListStaleSecretsRow, error) {
	rows, err := q.db.Query(ctx, listStaleSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleSecretsRow
	for rows.Next() {
		var i ListStaleSecretsRow
		if err := rows.Scan(
			&i.SecretPath,
			&i.CustomerID,
			&i.Provenance,
			&i.RotationCadence,
			&i.LastRotatedAt,
			&i.LastAccessedAt,
			&i.AllowedRoleSlugs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSecretLastAccessed = `-- name: TouchSecretLastAccessed :exec
UPDATE secret_metadata
   SET last_accessed_at = $1,
       updated_at       = now()
 WHERE secret_path = $2 AND customer_id = $3
`

type TouchSecretLastAccessedParams struct {
	LastAccessedAt pgtype.Timestamptz
	SecretPath     string
	CustomerID     pgtype.UUID
}

// Called by vault.WriteAuditRow on OutcomeGranted to update
// secret_metadata.last_accessed_at (D3.4 from plan). Same transaction as
// the vault_access_log INSERT.
func (q *Queries) TouchSecretLastAccessed(ctx context.Context, arg TouchSecretLastAccessedParams) error {
	_, err := q.db.Exec(ctx, touchSecretLastAccessed, arg.LastAccessedAt, arg.SecretPath, arg.CustomerID)
	return err
}

const upsertSecretMetadata = `-- name: UpsertSecretMetadata :exec
INSERT INTO secret_metadata
    (secret_path, customer_id, provenance, rotation_cadence, last_rotated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (secret_path, customer_id) DO UPDATE
    SET provenance       = EXCLUDED.provenance,
        rotation_cadence = EXCLUDED.rotation_cadence,
        last_rotated_at  = EXCLUDED.last_rotated_at,
        updated_at       = now()
`

type UpsertSecretMetadataParams struct {
	SecretPath      string
	CustomerID      pgtype.UUID
	Provenance      string
	RotationCadence pgtype.Interval
	LastRotatedAt   pgtype.Timestamptz
}

// M2.3 operator-driven seeding path (ops-checklist snippets). The trigger on
// agent_role_secrets keeps allowed_role_slugs in sync automatically.
func (q *Queries) UpsertSecretMetadata(ctx context.Context, arg UpsertSecretMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertSecretMetadata,
		arg.SecretPath,
		arg.CustomerID,
		arg.Provenance,
		arg.RotationCadence,
		arg.LastRotatedAt,
	)
	return err
}
