// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: throttle.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanyThrottleState = `-- name: GetCompanyThrottleState :one

SELECT
  c.id AS company_id,
  c.daily_budget_usd,
  c.pause_until,
  COALESCE(
    (SELECT SUM(ai.total_cost_usd)
       FROM agent_instances ai
       JOIN tickets t     ON t.id = ai.ticket_id
       JOIN departments d ON d.id = t.department_id
      WHERE d.company_id = c.id
        AND ai.started_at >= NOW() - INTERVAL '24 hours'),
    0
  )::NUMERIC(10,2) AS cost_24h_usd
FROM companies c
WHERE c.id = $1
`

type GetCompanyThrottleStateRow struct {
	CompanyID      pgtype.UUID
	DailyBudgetUsd pgtype.Numeric
	PauseUntil     pgtype.Timestamptz
	Cost24hUsd     pgtype.Numeric
}

// M6 throttle-actuator queries (spec FR-031, FR-033, FR-040..FR-044).
// All four run on the caller's transaction so the supervisor's
// spawn-prep gate + rate-limit observer can compose audit writes
// atomically with the side-effect (event_outbox row stays unprocessed
// for budget defer; pause_until UPDATE for rate-limit pause).
// Single read returning budget + pause + rolling-24h cost. The lateral
// subquery sums total_cost_usd across the company's department graph
// since NOW() - 24h; COALESCE handles companies with no agent_instances
// yet (returns 0 instead of NULL). The throttle gate only fires after
// US2 (FR-020) lands honest cost telemetry — until then, the sum reads
// low for clean-finalize runs (docs/issues/cost-telemetry-blind-spot.md).
func (q *Queries) GetCompanyThrottleState(ctx context.Context, id pgtype.UUID) (GetCompanyThrottleStateRow, error) {
	row := q.db.QueryRow(ctx, getCompanyThrottleState, id)
	var i GetCompanyThrottleStateRow
	err := row.Scan(
		&i.CompanyID,
		&i.DailyBudgetUsd,
		&i.PauseUntil,
		&i.Cost24hUsd,
	)
	return i, err
}

const insertThrottleEvent = `-- name: InsertThrottleEvent :one
INSERT INTO throttle_events (company_id, kind, payload)
VALUES ($1, $2, $3)
RETURNING id, company_id, kind, fired_at, payload
`

type InsertThrottleEventParams struct {
	CompanyID pgtype.UUID
	Kind      string
	Payload   []byte
}

// M6 T004: append-only audit row. kind is constrained at the schema
// level via CHECK; payload is JSONB carrying forensic detail (current
// spend + estimated next + budget for company_budget_exceeded;
// pause_until + back-off seconds for rate_limit_pause).
func (q *Queries) InsertThrottleEvent(ctx context.Context, arg InsertThrottleEventParams) (ThrottleEvent, error) {
	row := q.db.QueryRow(ctx, insertThrottleEvent, arg.CompanyID, arg.Kind, arg.Payload)
	var i ThrottleEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Kind,
		&i.FiredAt,
		&i.Payload,
	)
	return i, err
}

const listThrottleEventsByCompany = `-- name: ListThrottleEventsByCompany :many
SELECT id, company_id, kind, fired_at, payload
FROM throttle_events
WHERE company_id = $1
ORDER BY fired_at DESC
LIMIT $2
`

type ListThrottleEventsByCompanyParams struct {
	CompanyID pgtype.UUID
	Limit     int32
}

// M6 T016 read-side query for the dashboard hygiene throttle sub-table.
// ORDER BY fired_at DESC matches the dashboard's "most recent first"
// list shape; the (company_id, fired_at DESC) index serves this query
// directly with no sort step.
func (q *Queries) ListThrottleEventsByCompany(ctx context.Context, arg ListThrottleEventsByCompanyParams) ([]ThrottleEvent, error) {
	rows, err := q.db.Query(ctx, listThrottleEventsByCompany, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThrottleEvent
	for rows.Next() {
		var i ThrottleEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Kind,
			&i.FiredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyPauseUntil = `-- name: UpdateCompanyPauseUntil :exec
UPDATE companies
SET pause_until = $2
WHERE id = $1
`

type UpdateCompanyPauseUntilParams struct {
	ID         pgtype.UUID
	PauseUntil pgtype.Timestamptz
}

// M6 T008: rate-limit observer flips into actuator mode. Last write
// wins on concurrent rate-limit events for the same company; the
// throttle_events row carries the audit so both events are visible.
func (q *Queries) UpdateCompanyPauseUntil(ctx context.Context, arg UpdateCompanyPauseUntilParams) error {
	_, err := q.db.Exec(ctx, updateCompanyPauseUntil, arg.ID, arg.PauseUntil)
	return err
}
