// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ticket_transitions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStuckHygieneTransitions = `-- name: ListStuckHygieneTransitions :many
SELECT id,
       ticket_id,
       triggered_by_agent_instance_id,
       from_column,
       to_column,
       at,
       hygiene_status
FROM ticket_transitions
WHERE (hygiene_status IS NULL OR hygiene_status = 'pending')
  AND at < NOW() - $1::interval
ORDER BY at ASC
LIMIT $2
`

type ListStuckHygieneTransitionsParams struct {
	Column1 pgtype.Interval
	Limit   int32
}

type ListStuckHygieneTransitionsRow struct {
	ID                         pgtype.UUID
	TicketID                   pgtype.UUID
	TriggeredByAgentInstanceID pgtype.UUID
	FromColumn                 *string
	ToColumn                   string
	At                         pgtype.Timestamptz
	HygieneStatus              *string
}

// Rows older than the delay interval whose hygiene is unresolved. Used by
// the periodic sweep goroutine (FR-216) to recover rows the LISTEN path
// missed or couldn't evaluate (e.g. palace unreachable → StatusPending).
// $1 is the delay interval (e.g. '5 seconds'); $2 is the batch cap.
func (q *Queries) ListStuckHygieneTransitions(ctx context.Context, arg ListStuckHygieneTransitionsParams) ([]ListStuckHygieneTransitionsRow, error) {
	rows, err := q.db.Query(ctx, listStuckHygieneTransitions, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStuckHygieneTransitionsRow
	for rows.Next() {
		var i ListStuckHygieneTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.TriggeredByAgentInstanceID,
			&i.FromColumn,
			&i.ToColumn,
			&i.At,
			&i.HygieneStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketTransitionHygiene = `-- name: UpdateTicketTransitionHygiene :exec
UPDATE ticket_transitions
SET hygiene_status = $2
WHERE id = $1
  AND (hygiene_status IS NULL OR hygiene_status = 'pending')
`

type UpdateTicketTransitionHygieneParams struct {
	ID            pgtype.UUID
	HygieneStatus *string
}

// At-most-once-to-terminal per FR-215: only overwrites NULL or 'pending'.
// Once a terminal status (clean|missing_diary|missing_kg|thin) is set,
// subsequent calls for the same row are no-ops.
func (q *Queries) UpdateTicketTransitionHygiene(ctx context.Context, arg UpdateTicketTransitionHygieneParams) error {
	_, err := q.db.Exec(ctx, updateTicketTransitionHygiene, arg.ID, arg.HygieneStatus)
	return err
}
