// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, department_id, objective, created_at, column_slug, acceptance_criteria, metadata, origin, created_via_chat_session_id, parent_ticket_id FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
		&i.ColumnSlug,
		&i.AcceptanceCriteria,
		&i.Metadata,
		&i.Origin,
		&i.CreatedViaChatSessionID,
		&i.ParentTicketID,
	)
	return i, err
}

const getTicketColumnAndDept = `-- name: GetTicketColumnAndDept :one
SELECT column_slug, department_id FROM tickets WHERE id = $1
`

type GetTicketColumnAndDeptRow struct {
	ColumnSlug   string
	DepartmentID pgtype.UUID
}

// Pre-transition snapshot used by transition_ticket: returns the
// current column_slug + department_id so the verb can compute
// from_column for the audit row + ticket_transitions row.
func (q *Queries) GetTicketColumnAndDept(ctx context.Context, id pgtype.UUID) (GetTicketColumnAndDeptRow, error) {
	row := q.db.QueryRow(ctx, getTicketColumnAndDept, id)
	var i GetTicketColumnAndDeptRow
	err := row.Scan(&i.ColumnSlug, &i.DepartmentID)
	return i, err
}

const insertChatTicket = `-- name: InsertChatTicket :one
INSERT INTO tickets (
    department_id, objective, acceptance_criteria, column_slug,
    metadata, origin, created_via_chat_session_id, parent_ticket_id
)
VALUES ($1, $2, $3, $4, $5, 'ceo_chat', $6, $7)
RETURNING id, department_id, objective, created_at, column_slug, acceptance_criteria, metadata, origin, created_via_chat_session_id, parent_ticket_id
`

type InsertChatTicketParams struct {
	DepartmentID            pgtype.UUID
	Objective               string
	AcceptanceCriteria      *string
	ColumnSlug              string
	Metadata                []byte
	CreatedViaChatSessionID pgtype.UUID
	ParentTicketID          pgtype.UUID
}

// M5.3 garrison-mutate.create_ticket. Writes a ticket row with
// origin='ceo_chat' and the FK back to the originating chat session
// so forensic queries can join chat_session→tickets without
// needing chat_mutation_audit. Caller is the garrison-mutate verb's
// transaction; the audit row INSERT runs in the same tx.
// column_slug + metadata use NULLABLE sentinel inputs so the verb can
// pass NULL to mean "use default"; the verb resolves "todo" / "{}"
// before calling rather than relying on COALESCE-on-cast SQL that
// confuses sqlc's parameter-name inference.
// M6 T010: parent_ticket_id passes through as a NULLABLE sentinel; verb
// handler validates same-department + non-closed parent BEFORE calling
// this query (cross-table CHECK can't enforce both; verb error message
// has to be operator-readable anyway).
func (q *Queries) InsertChatTicket(ctx context.Context, arg InsertChatTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertChatTicket,
		arg.DepartmentID,
		arg.Objective,
		arg.AcceptanceCriteria,
		arg.ColumnSlug,
		arg.Metadata,
		arg.CreatedViaChatSessionID,
		arg.ParentTicketID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
		&i.ColumnSlug,
		&i.AcceptanceCriteria,
		&i.Metadata,
		&i.Origin,
		&i.CreatedViaChatSessionID,
		&i.ParentTicketID,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets (department_id, objective)
VALUES ($1, $2)
RETURNING id, department_id, objective, created_at, column_slug, acceptance_criteria, metadata, origin, created_via_chat_session_id, parent_ticket_id
`

type InsertTicketParams struct {
	DepartmentID pgtype.UUID
	Objective    string
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket, arg.DepartmentID, arg.Objective)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
		&i.ColumnSlug,
		&i.AcceptanceCriteria,
		&i.Metadata,
		&i.Origin,
		&i.CreatedViaChatSessionID,
		&i.ParentTicketID,
	)
	return i, err
}

const insertTicketTransition = `-- name: InsertTicketTransition :one
INSERT INTO ticket_transitions (ticket_id, from_column, to_column, triggered_by_agent_instance_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertTicketTransitionParams struct {
	TicketID                   pgtype.UUID
	FromColumn                 *string
	ToColumn                   string
	TriggeredByAgentInstanceID pgtype.UUID
}

func (q *Queries) InsertTicketTransition(ctx context.Context, arg InsertTicketTransitionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTicketTransition,
		arg.TicketID,
		arg.FromColumn,
		arg.ToColumn,
		arg.TriggeredByAgentInstanceID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockTicketForUpdate = `-- name: LockTicketForUpdate :one
SELECT id FROM tickets WHERE id = $1 FOR UPDATE NOWAIT
`

// M5.3 concurrent-mutation conflict resolution per chat-threat-model.md
// Rule 4 + plan §4.3. SELECT ... FOR UPDATE NOWAIT returns immediately
// with PostgreSQL error 55P03 (lock_not_available) if another tx holds
// the row lock. The verb maps that error to ErrTicketStateChanged.
func (q *Queries) LockTicketForUpdate(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockTicketForUpdate, id)
	err := row.Scan(&id)
	return id, err
}

const selectDepartmentIDBySlug = `-- name: SelectDepartmentIDBySlug :one
SELECT id FROM departments WHERE slug = $1
`

// garrison-mutate verbs accept department_slug from the chat assistant;
// internal queries use department_id (UUID). Resolves the slug→id
// before INSERT/UPDATE; returns no rows if the slug doesn't exist.
func (q *Queries) SelectDepartmentIDBySlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, selectDepartmentIDBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const selectTicketObjective = `-- name: SelectTicketObjective :one
SELECT objective FROM tickets WHERE id = $1
`

// M2.2.1: read the ticket's objective text for the FR-263 diary
// serialization — the supervisor's atomic writer prepends this prose
// to the drawer body so mempalace_search queries keyed on objective
// text return the drawer (semantic-similarity fails on raw UUIDs per
// M2.2 live-run finding).
func (q *Queries) SelectTicketObjective(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, selectTicketObjective, id)
	var objective string
	err := row.Scan(&objective)
	return objective, err
}

const updateTicketColumnSlug = `-- name: UpdateTicketColumnSlug :exec
UPDATE tickets SET column_slug = $2 WHERE id = $1
`

type UpdateTicketColumnSlugParams struct {
	ID         pgtype.UUID
	ColumnSlug string
}

func (q *Queries) UpdateTicketColumnSlug(ctx context.Context, arg UpdateTicketColumnSlugParams) error {
	_, err := q.db.Exec(ctx, updateTicketColumnSlug, arg.ID, arg.ColumnSlug)
	return err
}

const updateTicketEditableFields = `-- name: UpdateTicketEditableFields :exec
UPDATE tickets
   SET objective = $1,
       acceptance_criteria = $2,
       metadata = $3
 WHERE id = $4
`

type UpdateTicketEditableFieldsParams struct {
	Objective          string
	AcceptanceCriteria *string
	Metadata           []byte
	ID                 pgtype.UUID
}

// garrison-mutate.edit_ticket: partial update of operator-editable
// fields. The verb resolves COALESCE semantics on the Go side: it
// reads the before-state, merges with the args, and passes the
// final values here. metadata is JSONB; the Go side handles merge.
func (q *Queries) UpdateTicketEditableFields(ctx context.Context, arg UpdateTicketEditableFieldsParams) error {
	_, err := q.db.Exec(ctx, updateTicketEditableFields,
		arg.Objective,
		arg.AcceptanceCriteria,
		arg.Metadata,
		arg.ID,
	)
	return err
}
