// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, department_id, objective, created_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets (department_id, objective)
VALUES ($1, $2)
RETURNING id, department_id, objective, created_at
`

type InsertTicketParams struct {
	DepartmentID pgtype.UUID
	Objective    string
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket, arg.DepartmentID, arg.Objective)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
	)
	return i, err
}
