// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, department_id, objective, created_at, column_slug, acceptance_criteria, metadata, origin FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
		&i.ColumnSlug,
		&i.AcceptanceCriteria,
		&i.Metadata,
		&i.Origin,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets (department_id, objective)
VALUES ($1, $2)
RETURNING id, department_id, objective, created_at, column_slug, acceptance_criteria, metadata, origin
`

type InsertTicketParams struct {
	DepartmentID pgtype.UUID
	Objective    string
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket, arg.DepartmentID, arg.Objective)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Objective,
		&i.CreatedAt,
		&i.ColumnSlug,
		&i.AcceptanceCriteria,
		&i.Metadata,
		&i.Origin,
	)
	return i, err
}

const insertTicketTransition = `-- name: InsertTicketTransition :one
INSERT INTO ticket_transitions (ticket_id, from_column, to_column, triggered_by_agent_instance_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertTicketTransitionParams struct {
	TicketID                   pgtype.UUID
	FromColumn                 *string
	ToColumn                   string
	TriggeredByAgentInstanceID pgtype.UUID
}

func (q *Queries) InsertTicketTransition(ctx context.Context, arg InsertTicketTransitionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTicketTransition,
		arg.TicketID,
		arg.FromColumn,
		arg.ToColumn,
		arg.TriggeredByAgentInstanceID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateTicketColumnSlug = `-- name: UpdateTicketColumnSlug :exec
UPDATE tickets SET column_slug = $2 WHERE id = $1
`

type UpdateTicketColumnSlugParams struct {
	ID         pgtype.UUID
	ColumnSlug string
}

func (q *Queries) UpdateTicketColumnSlug(ctx context.Context, arg UpdateTicketColumnSlugParams) error {
	_, err := q.db.Exec(ctx, updateTicketColumnSlug, arg.ID, arg.ColumnSlug)
	return err
}
