// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vault_access_log.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertVaultAccessLog = `-- name: InsertVaultAccessLog :exec
INSERT INTO vault_access_log
    (agent_instance_id, ticket_id, secret_path, customer_id, outcome, timestamp)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVaultAccessLogParams struct {
	AgentInstanceID pgtype.UUID
	TicketID        pgtype.UUID
	SecretPath      string
	CustomerID      pgtype.UUID
	Outcome         string
	Timestamp       pgtype.Timestamptz
}

// FR-412: append-only; no UPDATE / DELETE paths. customer_id carried for
// future multi-tenant partitioning. No secret-value column by design.
func (q *Queries) InsertVaultAccessLog(ctx context.Context, arg InsertVaultAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertVaultAccessLog,
		arg.AgentInstanceID,
		arg.TicketID,
		arg.SecretPath,
		arg.CustomerID,
		arg.Outcome,
		arg.Timestamp,
	)
	return err
}

const listVaultAccessByTicket = `-- name: ListVaultAccessByTicket :many
SELECT id, agent_instance_id, secret_path, outcome, timestamp
  FROM vault_access_log
 WHERE ticket_id = $1
 ORDER BY timestamp DESC
`

type ListVaultAccessByTicketRow struct {
	ID              pgtype.UUID
	AgentInstanceID pgtype.UUID
	SecretPath      string
	Outcome         string
	Timestamp       pgtype.Timestamptz
}

// Exists specifically for M3's dashboard; M2.3 does not call this query.
func (q *Queries) ListVaultAccessByTicket(ctx context.Context, ticketID pgtype.UUID) ([]ListVaultAccessByTicketRow, error) {
	rows, err := q.db.Query(ctx, listVaultAccessByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaultAccessByTicketRow
	for rows.Next() {
		var i ListVaultAccessByTicketRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentInstanceID,
			&i.SecretPath,
			&i.Outcome,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
